


import re
import collections

from enum import Enum

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum, _dm_validate_value
from ydk.types import Empty, YList, DELETE, Decimal64, FixedBitsDict
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_CLASS, REFERENCE_LIST, REFERENCE_LEAFLIST,     REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, REFERENCE_BITS, REFERENCE_UNION

from ydk.errors import YPYError, YPYDataValidationError
from ydk.models import _yang_ns

_meta_table = {
    'SNMPTARGETMIB.SnmpTargetAddrTable.SnmpTargetAddrEntry' : {
        'meta_info' : _MetaInfoClass('SNMPTARGETMIB.SnmpTargetAddrTable.SnmpTargetAddrEntry',
            False, 
            [
            _MetaInfoClassMember('snmpTargetAddrName', ATTRIBUTE, 'str' , None, None, 
                [(1, 32)], [], 
                '''                ''',
                'snmptargetaddrname',
                'SNMP-TARGET-MIB', True),
            _MetaInfoClassMember('enabled', ATTRIBUTE, 'bool' , None, None, 
                [], [], 
                '''                ''',
                'enabled',
                'SNMP-TARGET-MIB', False),
            _MetaInfoClassMember('snmpTargetAddrEngineID', ATTRIBUTE, 'str' , None, None, 
                [], ['(([0-9a-fA-F]){2}(:([0-9a-fA-F]){2})*)?'], 
                '''                ''',
                'snmptargetaddrengineid',
                'SNMP-TARGET-MIB', False),
            _MetaInfoClassMember('snmpTargetAddrMMS', ATTRIBUTE, 'int' , None, None, 
                [(0, None), (484, 2147483647)], [], 
                '''                ''',
                'snmptargetaddrmms',
                'SNMP-TARGET-MIB', False),
            _MetaInfoClassMember('snmpTargetAddrParams', ATTRIBUTE, 'str' , None, None, 
                [(1, 32)], [], 
                '''                ''',
                'snmptargetaddrparams',
                'SNMP-TARGET-MIB', False),
            _MetaInfoClassMember('snmpTargetAddrRetryCount', ATTRIBUTE, 'int' , None, None, 
                [(0, 255)], [], 
                '''                ''',
                'snmptargetaddrretrycount',
                'SNMP-TARGET-MIB', False),
            _MetaInfoClassMember('snmpTargetAddrStorageType', REFERENCE_ENUM_CLASS, 'StorageType_Enum' , 'ydk.models.snmpv2.SNMPv2_TC', 'StorageType_Enum', 
                [], [], 
                '''                ''',
                'snmptargetaddrstoragetype',
                'SNMP-TARGET-MIB', False),
            _MetaInfoClassMember('snmpTargetAddrTAddress', REFERENCE_UNION, 'str' , None, None, 
                [], [], 
                '''                ''',
                'snmptargetaddrtaddress',
                'SNMP-TARGET-MIB', False, [
                    _MetaInfoClassMember('snmpTargetAddrTAddress', ATTRIBUTE, 'str' , None, None, 
                        [], ['(\\d*(.\\d*)*)?'], 
                        '''                        ''',
                        'snmptargetaddrtaddress',
                        'SNMP-TARGET-MIB', False),
                    _MetaInfoClassMember('snmpTargetAddrTAddress', ATTRIBUTE, 'str' , None, None, 
                        [], ['(\\d*(.\\d*)*)?'], 
                        '''                        ''',
                        'snmptargetaddrtaddress',
                        'SNMP-TARGET-MIB', False),
                ]),
            _MetaInfoClassMember('snmpTargetAddrTagList', ATTRIBUTE, 'str' , None, None, 
                [('0', 255)], [], 
                '''                ''',
                'snmptargetaddrtaglist',
                'SNMP-TARGET-MIB', False),
            _MetaInfoClassMember('snmpTargetAddrTDomain', ATTRIBUTE, 'str' , None, None, 
                [], ['(([0-1](\\.[1-3]?[0-9]))|(2\\.(0|([1-9]\\d*))))(\\.(0|([1-9]\\d*)))*'], 
                '''                ''',
                'snmptargetaddrtdomain',
                'SNMP-TARGET-MIB', False),
            _MetaInfoClassMember('snmpTargetAddrTimeout', ATTRIBUTE, 'int' , None, None, 
                [(0, 2147483647)], [], 
                '''                ''',
                'snmptargetaddrtimeout',
                'SNMP-TARGET-MIB', False),
            _MetaInfoClassMember('snmpTargetAddrTMask', REFERENCE_UNION, 'str' , None, None, 
                [], [], 
                '''                ''',
                'snmptargetaddrtmask',
                'SNMP-TARGET-MIB', False, [
                    _MetaInfoClassMember('snmpTargetAddrTMask', REFERENCE_UNION, 'str' , None, None, 
                        [], [], 
                        '''                        ''',
                        'snmptargetaddrtmask',
                        'SNMP-TARGET-MIB', False, [
                            _MetaInfoClassMember('snmpTargetAddrTMask', ATTRIBUTE, 'str' , None, None, 
                                [], ['(\\d*(.\\d*)*)?'], 
                                '''                                ''',
                                'snmptargetaddrtmask',
                                'SNMP-TARGET-MIB', False),
                            _MetaInfoClassMember('snmpTargetAddrTMask', ATTRIBUTE, 'str' , None, None, 
                                [], ['(\\d*(.\\d*)*)?'], 
                                '''                                ''',
                                'snmptargetaddrtmask',
                                'SNMP-TARGET-MIB', False),
                        ]),
                    _MetaInfoClassMember('snmpTargetAddrTMask', ATTRIBUTE, 'str' , None, None, 
                        [], ['(\\d*(.\\d*)*)?'], 
                        '''                        ''',
                        'snmptargetaddrtmask',
                        'SNMP-TARGET-MIB', False),
                ]),
            ],
            'SNMP-TARGET-MIB',
            'snmpTargetAddrEntry',
            _yang_ns._namespaces['SNMP-TARGET-MIB'],
        'ydk.models.snmp.SNMP_TARGET_MIB'
        ),
    },
    'SNMPTARGETMIB.SnmpTargetAddrTable' : {
        'meta_info' : _MetaInfoClass('SNMPTARGETMIB.SnmpTargetAddrTable',
            False, 
            [
            _MetaInfoClassMember('snmpTargetAddrEntry', REFERENCE_LIST, 'SnmpTargetAddrEntry' , 'ydk.models.snmp.SNMP_TARGET_MIB', 'SNMPTARGETMIB.SnmpTargetAddrTable.SnmpTargetAddrEntry', 
                [], [], 
                '''                ''',
                'snmptargetaddrentry',
                'SNMP-TARGET-MIB', False),
            ],
            'SNMP-TARGET-MIB',
            'snmpTargetAddrTable',
            _yang_ns._namespaces['SNMP-TARGET-MIB'],
        'ydk.models.snmp.SNMP_TARGET_MIB'
        ),
    },
    'SNMPTARGETMIB.SnmpTargetObjects' : {
        'meta_info' : _MetaInfoClass('SNMPTARGETMIB.SnmpTargetObjects',
            False, 
            [
            _MetaInfoClassMember('snmpUnavailableContexts', ATTRIBUTE, 'int' , None, None, 
                [(0, 4294967295)], [], 
                '''                ''',
                'snmpunavailablecontexts',
                'SNMP-TARGET-MIB', False),
            _MetaInfoClassMember('snmpUnknownContexts', ATTRIBUTE, 'int' , None, None, 
                [(0, 4294967295)], [], 
                '''                ''',
                'snmpunknowncontexts',
                'SNMP-TARGET-MIB', False),
            ],
            'SNMP-TARGET-MIB',
            'snmpTargetObjects',
            _yang_ns._namespaces['SNMP-TARGET-MIB'],
        'ydk.models.snmp.SNMP_TARGET_MIB'
        ),
    },
    'SNMPTARGETMIB.SnmpTargetParamsTable.SnmpTargetParamsEntry' : {
        'meta_info' : _MetaInfoClass('SNMPTARGETMIB.SnmpTargetParamsTable.SnmpTargetParamsEntry',
            False, 
            [
            _MetaInfoClassMember('snmpTargetParamsName', ATTRIBUTE, 'str' , None, None, 
                [(1, 32)], [], 
                '''                ''',
                'snmptargetparamsname',
                'SNMP-TARGET-MIB', True),
            _MetaInfoClassMember('snmpTargetParamsMPModel', ATTRIBUTE, 'int' , None, None, 
                [(0, 2147483647)], [], 
                '''                ''',
                'snmptargetparamsmpmodel',
                'SNMP-TARGET-MIB', False),
            _MetaInfoClassMember('snmpTargetParamsSecurityLevel', REFERENCE_ENUM_CLASS, 'SnmpSecurityLevel_Enum' , 'ydk.models.snmp.SNMP_FRAMEWORK_MIB', 'SnmpSecurityLevel_Enum', 
                [], [], 
                '''                ''',
                'snmptargetparamssecuritylevel',
                'SNMP-TARGET-MIB', False),
            _MetaInfoClassMember('snmpTargetParamsSecurityModel', ATTRIBUTE, 'int' , None, None, 
                [(1, 2147483647)], [], 
                '''                ''',
                'snmptargetparamssecuritymodel',
                'SNMP-TARGET-MIB', False),
            _MetaInfoClassMember('snmpTargetParamsSecurityName', ATTRIBUTE, 'str' , None, None, 
                [('0', 255)], [], 
                '''                ''',
                'snmptargetparamssecurityname',
                'SNMP-TARGET-MIB', False),
            _MetaInfoClassMember('snmpTargetParamsStorageType', REFERENCE_ENUM_CLASS, 'StorageType_Enum' , 'ydk.models.snmpv2.SNMPv2_TC', 'StorageType_Enum', 
                [], [], 
                '''                ''',
                'snmptargetparamsstoragetype',
                'SNMP-TARGET-MIB', False),
            ],
            'SNMP-TARGET-MIB',
            'snmpTargetParamsEntry',
            _yang_ns._namespaces['SNMP-TARGET-MIB'],
        'ydk.models.snmp.SNMP_TARGET_MIB'
        ),
    },
    'SNMPTARGETMIB.SnmpTargetParamsTable' : {
        'meta_info' : _MetaInfoClass('SNMPTARGETMIB.SnmpTargetParamsTable',
            False, 
            [
            _MetaInfoClassMember('snmpTargetParamsEntry', REFERENCE_LIST, 'SnmpTargetParamsEntry' , 'ydk.models.snmp.SNMP_TARGET_MIB', 'SNMPTARGETMIB.SnmpTargetParamsTable.SnmpTargetParamsEntry', 
                [], [], 
                '''                ''',
                'snmptargetparamsentry',
                'SNMP-TARGET-MIB', False),
            ],
            'SNMP-TARGET-MIB',
            'snmpTargetParamsTable',
            _yang_ns._namespaces['SNMP-TARGET-MIB'],
        'ydk.models.snmp.SNMP_TARGET_MIB'
        ),
    },
    'SNMPTARGETMIB' : {
        'meta_info' : _MetaInfoClass('SNMPTARGETMIB',
            False, 
            [
            _MetaInfoClassMember('snmpTargetAddrTable', REFERENCE_CLASS, 'SnmpTargetAddrTable' , 'ydk.models.snmp.SNMP_TARGET_MIB', 'SNMPTARGETMIB.SnmpTargetAddrTable', 
                [], [], 
                '''                ''',
                'snmptargetaddrtable',
                'SNMP-TARGET-MIB', False),
            _MetaInfoClassMember('snmpTargetObjects', REFERENCE_CLASS, 'SnmpTargetObjects' , 'ydk.models.snmp.SNMP_TARGET_MIB', 'SNMPTARGETMIB.SnmpTargetObjects', 
                [], [], 
                '''                ''',
                'snmptargetobjects',
                'SNMP-TARGET-MIB', False),
            _MetaInfoClassMember('snmpTargetParamsTable', REFERENCE_CLASS, 'SnmpTargetParamsTable' , 'ydk.models.snmp.SNMP_TARGET_MIB', 'SNMPTARGETMIB.SnmpTargetParamsTable', 
                [], [], 
                '''                ''',
                'snmptargetparamstable',
                'SNMP-TARGET-MIB', False),
            ],
            'SNMP-TARGET-MIB',
            'SNMP-TARGET-MIB',
            _yang_ns._namespaces['SNMP-TARGET-MIB'],
        'ydk.models.snmp.SNMP_TARGET_MIB'
        ),
    },
}
_meta_table['SNMPTARGETMIB.SnmpTargetAddrTable.SnmpTargetAddrEntry']['meta_info'].parent =_meta_table['SNMPTARGETMIB.SnmpTargetAddrTable']['meta_info']
_meta_table['SNMPTARGETMIB.SnmpTargetParamsTable.SnmpTargetParamsEntry']['meta_info'].parent =_meta_table['SNMPTARGETMIB.SnmpTargetParamsTable']['meta_info']
_meta_table['SNMPTARGETMIB.SnmpTargetAddrTable']['meta_info'].parent =_meta_table['SNMPTARGETMIB']['meta_info']
_meta_table['SNMPTARGETMIB.SnmpTargetObjects']['meta_info'].parent =_meta_table['SNMPTARGETMIB']['meta_info']
_meta_table['SNMPTARGETMIB.SnmpTargetParamsTable']['meta_info'].parent =_meta_table['SNMPTARGETMIB']['meta_info']
