


import re
import collections

from enum import Enum

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum, _dm_validate_value
from ydk.types import Empty, YList, DELETE, Decimal64, FixedBitsDict
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_CLASS, REFERENCE_LIST, REFERENCE_LEAFLIST,     REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, REFERENCE_BITS, REFERENCE_UNION

from ydk.errors import YPYError, YPYDataValidationError
from ydk.models import _yang_ns

_meta_table = {
    'SNMPUSERBASEDSMMIB.UsmStats' : {
        'meta_info' : _MetaInfoClass('SNMPUSERBASEDSMMIB.UsmStats',
            False, 
            [
            _MetaInfoClassMember('usmStatsDecryptionErrors', ATTRIBUTE, 'int' , None, None, 
                [(0, 4294967295)], [], 
                '''                ''',
                'usmstatsdecryptionerrors',
                'SNMP-USER-BASED-SM-MIB', False),
            _MetaInfoClassMember('usmStatsNotInTimeWindows', ATTRIBUTE, 'int' , None, None, 
                [(0, 4294967295)], [], 
                '''                ''',
                'usmstatsnotintimewindows',
                'SNMP-USER-BASED-SM-MIB', False),
            _MetaInfoClassMember('usmStatsUnknownEngineIDs', ATTRIBUTE, 'int' , None, None, 
                [(0, 4294967295)], [], 
                '''                ''',
                'usmstatsunknownengineids',
                'SNMP-USER-BASED-SM-MIB', False),
            _MetaInfoClassMember('usmStatsUnknownUserNames', ATTRIBUTE, 'int' , None, None, 
                [(0, 4294967295)], [], 
                '''                ''',
                'usmstatsunknownusernames',
                'SNMP-USER-BASED-SM-MIB', False),
            _MetaInfoClassMember('usmStatsUnsupportedSecLevels', ATTRIBUTE, 'int' , None, None, 
                [(0, 4294967295)], [], 
                '''                ''',
                'usmstatsunsupportedseclevels',
                'SNMP-USER-BASED-SM-MIB', False),
            _MetaInfoClassMember('usmStatsWrongDigests', ATTRIBUTE, 'int' , None, None, 
                [(0, 4294967295)], [], 
                '''                ''',
                'usmstatswrongdigests',
                'SNMP-USER-BASED-SM-MIB', False),
            ],
            'SNMP-USER-BASED-SM-MIB',
            'usmStats',
            _yang_ns._namespaces['SNMP-USER-BASED-SM-MIB'],
        'ydk.models.snmp.SNMP_USER_BASED_SM_MIB'
        ),
    },
    'SNMPUSERBASEDSMMIB.UsmUserTable.UsmUserEntry' : {
        'meta_info' : _MetaInfoClass('SNMPUSERBASEDSMMIB.UsmUserTable.UsmUserEntry',
            False, 
            [
            _MetaInfoClassMember('usmUserEngineID', ATTRIBUTE, 'str' , None, None, 
                [], ['(([0-9a-fA-F]){2}(:([0-9a-fA-F]){2})*)?'], 
                '''                ''',
                'usmuserengineid',
                'SNMP-USER-BASED-SM-MIB', True),
            _MetaInfoClassMember('usmUserName', ATTRIBUTE, 'str' , None, None, 
                [(1, 32)], [], 
                '''                ''',
                'usmusername',
                'SNMP-USER-BASED-SM-MIB', True),
            _MetaInfoClassMember('usmUserAuthKey', ATTRIBUTE, 'str' , None, None, 
                [], ['(([0-9a-fA-F]){2}(:([0-9a-fA-F]){2})*)?'], 
                '''                ''',
                'usmuserauthkey',
                'SNMP-USER-BASED-SM-MIB', False),
            _MetaInfoClassMember('usmUserAuthKeyChange', ATTRIBUTE, 'str' , None, None, 
                [], ['(([0-9a-fA-F]){2}(:([0-9a-fA-F]){2})*)?'], 
                '''                ''',
                'usmuserauthkeychange',
                'SNMP-USER-BASED-SM-MIB', False),
            _MetaInfoClassMember('usmUserAuthProtocol', ATTRIBUTE, 'str' , None, None, 
                [], ['(([0-1](\\.[1-3]?[0-9]))|(2\\.(0|([1-9]\\d*))))(\\.(0|([1-9]\\d*)))*'], 
                '''                ''',
                'usmuserauthprotocol',
                'SNMP-USER-BASED-SM-MIB', False),
            _MetaInfoClassMember('usmUserCloneFrom', ATTRIBUTE, 'str' , None, None, 
                [], ['(([0-1](\\.[1-3]?[0-9]))|(2\\.(0|([1-9]\\d*))))(\\.(0|([1-9]\\d*)))*'], 
                '''                ''',
                'usmuserclonefrom',
                'SNMP-USER-BASED-SM-MIB', False),
            _MetaInfoClassMember('usmUserOwnAuthKeyChange', ATTRIBUTE, 'str' , None, None, 
                [], ['(([0-9a-fA-F]){2}(:([0-9a-fA-F]){2})*)?'], 
                '''                ''',
                'usmuserownauthkeychange',
                'SNMP-USER-BASED-SM-MIB', False),
            _MetaInfoClassMember('usmUserOwnPrivKeyChange', ATTRIBUTE, 'str' , None, None, 
                [], ['(([0-9a-fA-F]){2}(:([0-9a-fA-F]){2})*)?'], 
                '''                ''',
                'usmuserownprivkeychange',
                'SNMP-USER-BASED-SM-MIB', False),
            _MetaInfoClassMember('usmUserPrivKey', ATTRIBUTE, 'str' , None, None, 
                [], ['(([0-9a-fA-F]){2}(:([0-9a-fA-F]){2})*)?'], 
                '''                ''',
                'usmuserprivkey',
                'SNMP-USER-BASED-SM-MIB', False),
            _MetaInfoClassMember('usmUserPrivKeyChange', ATTRIBUTE, 'str' , None, None, 
                [], ['(([0-9a-fA-F]){2}(:([0-9a-fA-F]){2})*)?'], 
                '''                ''',
                'usmuserprivkeychange',
                'SNMP-USER-BASED-SM-MIB', False),
            _MetaInfoClassMember('usmUserPrivProtocol', ATTRIBUTE, 'str' , None, None, 
                [], ['(([0-1](\\.[1-3]?[0-9]))|(2\\.(0|([1-9]\\d*))))(\\.(0|([1-9]\\d*)))*'], 
                '''                ''',
                'usmuserprivprotocol',
                'SNMP-USER-BASED-SM-MIB', False),
            _MetaInfoClassMember('usmUserPublic', ATTRIBUTE, 'str' , None, None, 
                [], ['(([0-9a-fA-F]){2}(:([0-9a-fA-F]){2})*)?'], 
                '''                ''',
                'usmuserpublic',
                'SNMP-USER-BASED-SM-MIB', False),
            _MetaInfoClassMember('usmUserSecurityName', ATTRIBUTE, 'str' , None, None, 
                [('0', 255)], [], 
                '''                ''',
                'usmusersecurityname',
                'SNMP-USER-BASED-SM-MIB', False),
            _MetaInfoClassMember('usmUserStorageType', REFERENCE_ENUM_CLASS, 'StorageType_Enum' , 'ydk.models.snmpv2.SNMPv2_TC', 'StorageType_Enum', 
                [], [], 
                '''                ''',
                'usmuserstoragetype',
                'SNMP-USER-BASED-SM-MIB', False),
            ],
            'SNMP-USER-BASED-SM-MIB',
            'usmUserEntry',
            _yang_ns._namespaces['SNMP-USER-BASED-SM-MIB'],
        'ydk.models.snmp.SNMP_USER_BASED_SM_MIB'
        ),
    },
    'SNMPUSERBASEDSMMIB.UsmUserTable' : {
        'meta_info' : _MetaInfoClass('SNMPUSERBASEDSMMIB.UsmUserTable',
            False, 
            [
            _MetaInfoClassMember('usmUserEntry', REFERENCE_LIST, 'UsmUserEntry' , 'ydk.models.snmp.SNMP_USER_BASED_SM_MIB', 'SNMPUSERBASEDSMMIB.UsmUserTable.UsmUserEntry', 
                [], [], 
                '''                ''',
                'usmuserentry',
                'SNMP-USER-BASED-SM-MIB', False),
            ],
            'SNMP-USER-BASED-SM-MIB',
            'usmUserTable',
            _yang_ns._namespaces['SNMP-USER-BASED-SM-MIB'],
        'ydk.models.snmp.SNMP_USER_BASED_SM_MIB'
        ),
    },
    'SNMPUSERBASEDSMMIB' : {
        'meta_info' : _MetaInfoClass('SNMPUSERBASEDSMMIB',
            False, 
            [
            _MetaInfoClassMember('usmStats', REFERENCE_CLASS, 'UsmStats' , 'ydk.models.snmp.SNMP_USER_BASED_SM_MIB', 'SNMPUSERBASEDSMMIB.UsmStats', 
                [], [], 
                '''                ''',
                'usmstats',
                'SNMP-USER-BASED-SM-MIB', False),
            _MetaInfoClassMember('usmUserTable', REFERENCE_CLASS, 'UsmUserTable' , 'ydk.models.snmp.SNMP_USER_BASED_SM_MIB', 'SNMPUSERBASEDSMMIB.UsmUserTable', 
                [], [], 
                '''                ''',
                'usmusertable',
                'SNMP-USER-BASED-SM-MIB', False),
            ],
            'SNMP-USER-BASED-SM-MIB',
            'SNMP-USER-BASED-SM-MIB',
            _yang_ns._namespaces['SNMP-USER-BASED-SM-MIB'],
        'ydk.models.snmp.SNMP_USER_BASED_SM_MIB'
        ),
    },
}
_meta_table['SNMPUSERBASEDSMMIB.UsmUserTable.UsmUserEntry']['meta_info'].parent =_meta_table['SNMPUSERBASEDSMMIB.UsmUserTable']['meta_info']
_meta_table['SNMPUSERBASEDSMMIB.UsmStats']['meta_info'].parent =_meta_table['SNMPUSERBASEDSMMIB']['meta_info']
_meta_table['SNMPUSERBASEDSMMIB.UsmUserTable']['meta_info'].parent =_meta_table['SNMPUSERBASEDSMMIB']['meta_info']
