


import re
import collections

from enum import Enum

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk.types import Empty, YList, YLeafList, DELETE, Decimal64, FixedBitsDict
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_CLASS, REFERENCE_LIST, REFERENCE_LEAFLIST,     REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, REFERENCE_BITS, REFERENCE_UNION, ANYXML_CLASS

from ydk.errors import YPYError, YPYModelError
from ydk.providers._importer import _yang_ns
_meta_table = {
    'FcportmoduletypesEnum' : _MetaInfoEnum('FcportmoduletypesEnum', 'ydk.models.cisco_ios_xe.CISCO_ST_TC',
        {
            'unknown':'unknown',
            'other':'other',
            'gbic':'gbic',
            'embedded':'embedded',
            'glm':'glm',
            'gbicWithSerialID':'gbicWithSerialID',
            'gbicWithoutSerialID':'gbicWithoutSerialID',
            'sfpWithSerialID':'sfpWithSerialID',
            'sfpWithoutSerialID':'sfpWithoutSerialID',
            'xfp':'xfp',
            'x2Short':'x2Short',
            'x2Medium':'x2Medium',
            'x2Tall':'x2Tall',
            'xpakShort':'xpakShort',
            'xpakMedium':'xpakMedium',
            'xpakTall':'xpakTall',
            'xenpak':'xenpak',
            'sfpDwdm':'sfpDwdm',
            'qsfp':'qsfp',
            'x2Dwdm':'x2Dwdm',
        }, 'CISCO-ST-TC', _yang_ns._namespaces['CISCO-ST-TC']),
    'FcifsfpdiagleveltypeEnum' : _MetaInfoEnum('FcifsfpdiagleveltypeEnum', 'ydk.models.cisco_ios_xe.CISCO_ST_TC',
        {
            'unknown':'unknown',
            'normal':'normal',
            'lowWarning':'lowWarning',
            'lowAlarm':'lowAlarm',
            'highWarning':'highWarning',
            'highAlarm':'highAlarm',
        }, 'CISCO-ST-TC', _yang_ns._namespaces['CISCO-ST-TC']),
    'FcaddresstypeEnum' : _MetaInfoEnum('FcaddresstypeEnum', 'ydk.models.cisco_ios_xe.CISCO_ST_TC',
        {
            'wwn':'wwn',
            'fcid':'fcid',
        }, 'CISCO-ST-TC', _yang_ns._namespaces['CISCO-ST-TC']),
    'InterfaceopermodeEnum' : _MetaInfoEnum('InterfaceopermodeEnum', 'ydk.models.cisco_ios_xe.CISCO_ST_TC',
        {
            'auto':'auto',
            'fPort':'fPort',
            'flPort':'flPort',
            'ePort':'ePort',
            'bPort':'bPort',
            'fxPort':'fxPort',
            'sdPort':'sdPort',
            'tlPort':'tlPort',
            'nPort':'nPort',
            'nlPort':'nlPort',
            'nxPort':'nxPort',
            'tePort':'tePort',
            'fvPort':'fvPort',
            'portOperDown':'portOperDown',
            'stPort':'stPort',
            'mgmtPort':'mgmtPort',
            'ipsPort':'ipsPort',
            'evPort':'evPort',
            'npPort':'npPort',
            'tfPort':'tfPort',
            'tnpPort':'tnpPort',
        }, 'CISCO-ST-TC', _yang_ns._namespaces['CISCO-ST-TC']),
    'FcporttxtypesEnum' : _MetaInfoEnum('FcporttxtypesEnum', 'ydk.models.cisco_ios_xe.CISCO_ST_TC',
        {
            'unknown':'unknown',
            'longWaveLaser':'longWaveLaser',
            'shortWaveLaser':'shortWaveLaser',
            'longWaveLaserCostReduced':'longWaveLaserCostReduced',
            'electrical':'electrical',
            'tenGigBaseSr':'tenGigBaseSr',
            'tenGigBaseLr':'tenGigBaseLr',
            'tenGigBaseEr':'tenGigBaseEr',
            'tenGigBaseLx4':'tenGigBaseLx4',
            'tenGigBaseSw':'tenGigBaseSw',
            'tenGigBaseLw':'tenGigBaseLw',
            'tenGigBaseEw':'tenGigBaseEw',
        }, 'CISCO-ST-TC', _yang_ns._namespaces['CISCO-ST-TC']),
    'FcifspeedEnum' : _MetaInfoEnum('FcifspeedEnum', 'ydk.models.cisco_ios_xe.CISCO_ST_TC',
        {
            'auto':'auto',
            'oneG':'oneG',
            'twoG':'twoG',
            'fourG':'fourG',
            'autoMaxTwoG':'autoMaxTwoG',
            'eightG':'eightG',
            'autoMaxFourG':'autoMaxFourG',
            'tenG':'tenG',
            'autoMaxEightG':'autoMaxEightG',
            'sixteenG':'sixteenG',
            'autoMaxSixteenG':'autoMaxSixteenG',
        }, 'CISCO-ST-TC', _yang_ns._namespaces['CISCO-ST-TC']),
    'FcporttypesEnum' : _MetaInfoEnum('FcporttypesEnum', 'ydk.models.cisco_ios_xe.CISCO_ST_TC',
        {
            'auto':'auto',
            'fPort':'fPort',
            'flPort':'flPort',
            'ePort':'ePort',
            'bPort':'bPort',
            'fxPort':'fxPort',
            'sdPort':'sdPort',
            'tlPort':'tlPort',
            'nPort':'nPort',
            'nlPort':'nlPort',
            'nxPort':'nxPort',
            'tePort':'tePort',
            'fvPort':'fvPort',
            'portOperDown':'portOperDown',
            'stPort':'stPort',
            'npPort':'npPort',
            'tfPort':'tfPort',
            'tnpPort':'tnpPort',
        }, 'CISCO-ST-TC', _yang_ns._namespaces['CISCO-ST-TC']),
    'FcifservicestatetypeEnum' : _MetaInfoEnum('FcifservicestatetypeEnum', 'ydk.models.cisco_ios_xe.CISCO_ST_TC',
        {
            'inService':'inService',
            'outOfService':'outOfService',
        }, 'CISCO-ST-TC', _yang_ns._namespaces['CISCO-ST-TC']),
}
