


import re
import collections

from enum import Enum

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk.types import Empty, YList, YLeafList, DELETE, Decimal64, FixedBitsDict
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_CLASS, REFERENCE_LIST, REFERENCE_LEAFLIST,     REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, REFERENCE_BITS, REFERENCE_UNION, ANYXML_CLASS

from ydk.errors import YPYError, YPYModelError
from ydk.providers._importer import _yang_ns
_meta_table = {
    'BuiltinmodesEnum' : _MetaInfoEnum('BuiltinmodesEnum', 'ydk.models.cisco_ios_xe.tailf_aaa',
        {
            'exec':'exec_',
            'configure':'configure',
        }, 'tailf-aaa', _yang_ns._namespaces['tailf-aaa']),
    'BuiltinmodesEnum' : _MetaInfoEnum('BuiltinmodesEnum', 'ydk.models.cisco_ios_xe.tailf_aaa',
        {
            'exec':'exec_',
            'configure':'configure',
        }, 'tailf-aaa', _yang_ns._namespaces['tailf-aaa']),
    'Aaa.Authentication.Users.User' : {
        'meta_info' : _MetaInfoClass('Aaa.Authentication.Users.User',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str' , None, None, 
                [], [], 
                '''                ''',
                'name',
                'tailf-aaa', True),
            _MetaInfoClassMember('gid', ATTRIBUTE, 'int' , None, None, 
                [('-2147483648', '2147483647')], [], 
                '''                ''',
                'gid',
                'tailf-aaa', False),
            _MetaInfoClassMember('homedir', ATTRIBUTE, 'str' , None, None, 
                [], [], 
                '''                ''',
                'homedir',
                'tailf-aaa', False),
            _MetaInfoClassMember('password', ATTRIBUTE, 'str' , None, None, 
                [], [b'$0$.*|$1$[a-zA-Z0-9./]{1,8}$[a-zA-Z0-9./]{22}|$5$(rounds=\\d+$)?[a-zA-Z0-9./]{1,16}$[a-zA-Z0-9./]{43}|$6$(rounds=\\d+$)?[a-zA-Z0-9./]{1,16}$[a-zA-Z0-9./]{86}'], 
                '''                ''',
                'password',
                'tailf-aaa', False),
            _MetaInfoClassMember('ssh_keydir', ATTRIBUTE, 'str' , None, None, 
                [], [], 
                '''                ''',
                'ssh_keydir',
                'tailf-aaa', False),
            _MetaInfoClassMember('uid', ATTRIBUTE, 'int' , None, None, 
                [('-2147483648', '2147483647')], [], 
                '''                ''',
                'uid',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'user',
            _yang_ns._namespaces['tailf-aaa'],
        'ydk.models.cisco_ios_xe.tailf_aaa'
        ),
    },
    'Aaa.Authentication.Users' : {
        'meta_info' : _MetaInfoClass('Aaa.Authentication.Users',
            False, 
            [
            _MetaInfoClassMember('user', REFERENCE_LIST, 'User' , 'ydk.models.cisco_ios_xe.tailf_aaa', 'Aaa.Authentication.Users.User', 
                [], [], 
                '''                ''',
                'user',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'users',
            _yang_ns._namespaces['tailf-aaa'],
        'ydk.models.cisco_ios_xe.tailf_aaa'
        ),
    },
    'Aaa.Authentication' : {
        'meta_info' : _MetaInfoClass('Aaa.Authentication',
            False, 
            [
            _MetaInfoClassMember('users', REFERENCE_CLASS, 'Users' , 'ydk.models.cisco_ios_xe.tailf_aaa', 'Aaa.Authentication.Users', 
                [], [], 
                '''                ''',
                'users',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'authentication',
            _yang_ns._namespaces['tailf-aaa'],
        'ydk.models.cisco_ios_xe.tailf_aaa'
        ),
    },
    'Aaa.Ios.Level' : {
        'meta_info' : _MetaInfoClass('Aaa.Ios.Level',
            False, 
            [
            _MetaInfoClassMember('nr', ATTRIBUTE, 'int' , None, None, 
                [('0', '15')], [], 
                '''                ''',
                'nr',
                'tailf-aaa', True),
            _MetaInfoClassMember('password', ATTRIBUTE, 'str' , None, None, 
                [], [b'$0$.*|$1$[a-zA-Z0-9./]{1,8}$[a-zA-Z0-9./]{22}|$5$(rounds=\\d+$)?[a-zA-Z0-9./]{1,16}$[a-zA-Z0-9./]{43}|$6$(rounds=\\d+$)?[a-zA-Z0-9./]{1,16}$[a-zA-Z0-9./]{86}'], 
                '''                ''',
                'password',
                'tailf-aaa', False),
            _MetaInfoClassMember('prompt', ATTRIBUTE, 'str' , None, None, 
                [], [], 
                '''                ''',
                'prompt',
                'tailf-aaa', False),
            _MetaInfoClassMember('secret', ATTRIBUTE, 'str' , None, None, 
                [], [b'$0$.*|$1$[a-zA-Z0-9./]{1,8}$[a-zA-Z0-9./]{22}|$5$(rounds=\\d+$)?[a-zA-Z0-9./]{1,16}$[a-zA-Z0-9./]{43}|$6$(rounds=\\d+$)?[a-zA-Z0-9./]{1,16}$[a-zA-Z0-9./]{86}'], 
                '''                ''',
                'secret',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'level',
            _yang_ns._namespaces['tailf-aaa'],
        'ydk.models.cisco_ios_xe.tailf_aaa'
        ),
    },
    'Aaa.Ios.Privilege.Level.Command' : {
        'meta_info' : _MetaInfoClass('Aaa.Ios.Privilege.Level.Command',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str' , None, None, 
                [], [], 
                '''                ''',
                'name',
                'tailf-aaa', True),
            ],
            'tailf-aaa',
            'command',
            _yang_ns._namespaces['tailf-aaa'],
        'ydk.models.cisco_ios_xe.tailf_aaa'
        ),
    },
    'Aaa.Ios.Privilege.Level' : {
        'meta_info' : _MetaInfoClass('Aaa.Ios.Privilege.Level',
            False, 
            [
            _MetaInfoClassMember('nr', ATTRIBUTE, 'int' , None, None, 
                [('0', '15')], [], 
                '''                ''',
                'nr',
                'tailf-aaa', True),
            _MetaInfoClassMember('command', REFERENCE_LIST, 'Command' , 'ydk.models.cisco_ios_xe.tailf_aaa', 'Aaa.Ios.Privilege.Level.Command', 
                [], [], 
                '''                ''',
                'command',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'level',
            _yang_ns._namespaces['tailf-aaa'],
        'ydk.models.cisco_ios_xe.tailf_aaa'
        ),
    },
    'Aaa.Ios.Privilege' : {
        'meta_info' : _MetaInfoClass('Aaa.Ios.Privilege',
            False, 
            [
            _MetaInfoClassMember('mode', REFERENCE_UNION, 'str' , None, None, 
                [], [], 
                '''                ''',
                'mode',
                'tailf-aaa', True, [
                    _MetaInfoClassMember('mode', ATTRIBUTE, 'str' , None, None, 
                        [], [], 
                        '''                        ''',
                        'mode',
                        'tailf-aaa', True),
                    _MetaInfoClassMember('mode', REFERENCE_ENUM_CLASS, 'BuiltinmodesEnum' , 'ydk.models.cisco_ios_xe.tailf_aaa', 'BuiltinmodesEnum', 
                        [], [], 
                        '''                        ''',
                        'mode',
                        'tailf-aaa', True),
                ]),
            _MetaInfoClassMember('level', REFERENCE_LIST, 'Level' , 'ydk.models.cisco_ios_xe.tailf_aaa', 'Aaa.Ios.Privilege.Level', 
                [], [], 
                '''                ''',
                'level',
                'tailf-aaa', False, max_elements=15, min_elements=1),
            ],
            'tailf-aaa',
            'privilege',
            _yang_ns._namespaces['tailf-aaa'],
        'ydk.models.cisco_ios_xe.tailf_aaa'
        ),
    },
    'Aaa.Ios' : {
        'meta_info' : _MetaInfoClass('Aaa.Ios',
            False, 
            [
            _MetaInfoClassMember('level', REFERENCE_LIST, 'Level' , 'ydk.models.cisco_ios_xe.tailf_aaa', 'Aaa.Ios.Level', 
                [], [], 
                '''                ''',
                'level',
                'tailf-aaa', False, min_elements=2),
            _MetaInfoClassMember('privilege', REFERENCE_LIST, 'Privilege' , 'ydk.models.cisco_ios_xe.tailf_aaa', 'Aaa.Ios.Privilege', 
                [], [], 
                '''                ''',
                'privilege',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'ios',
            _yang_ns._namespaces['tailf-aaa'],
        'ydk.models.cisco_ios_xe.tailf_aaa'
        ),
    },
    'Aaa' : {
        'meta_info' : _MetaInfoClass('Aaa',
            False, 
            [
            _MetaInfoClassMember('authentication', REFERENCE_CLASS, 'Authentication' , 'ydk.models.cisco_ios_xe.tailf_aaa', 'Aaa.Authentication', 
                [], [], 
                '''                ''',
                'authentication',
                'tailf-aaa', False),
            _MetaInfoClassMember('ios', REFERENCE_CLASS, 'Ios' , 'ydk.models.cisco_ios_xe.tailf_aaa', 'Aaa.Ios', 
                [], [], 
                '''                ''',
                'ios',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'aaa',
            _yang_ns._namespaces['tailf-aaa'],
        'ydk.models.cisco_ios_xe.tailf_aaa'
        ),
    },
    'Alias' : {
        'meta_info' : _MetaInfoClass('Alias',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str' , None, None, 
                [], [], 
                '''                ''',
                'name',
                'tailf-aaa', True),
            _MetaInfoClassMember('expansion', ATTRIBUTE, 'str' , None, None, 
                [], [], 
                '''                ''',
                'expansion',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'alias',
            _yang_ns._namespaces['tailf-aaa'],
        'ydk.models.cisco_ios_xe.tailf_aaa'
        ),
    },
    'Session' : {
        'meta_info' : _MetaInfoClass('Session',
            False, 
            [
            _MetaInfoClassMember('autowizard', ATTRIBUTE, 'bool' , None, None, 
                [], [], 
                '''                ''',
                'autowizard',
                'tailf-aaa', False),
            _MetaInfoClassMember('complete-on-space', ATTRIBUTE, 'bool' , None, None, 
                [], [], 
                '''                ''',
                'complete_on_space',
                'tailf-aaa', False),
            _MetaInfoClassMember('display-level', ATTRIBUTE, 'int' , None, None, 
                [('1', '64')], [], 
                '''                ''',
                'display_level',
                'tailf-aaa', False),
            _MetaInfoClassMember('history', ATTRIBUTE, 'int' , None, None, 
                [('0', '8192')], [], 
                '''                ''',
                'history',
                'tailf-aaa', False),
            _MetaInfoClassMember('idle-timeout', ATTRIBUTE, 'int' , None, None, 
                [('0', '8192')], [], 
                '''                ''',
                'idle_timeout',
                'tailf-aaa', False),
            _MetaInfoClassMember('ignore-leading-space', ATTRIBUTE, 'bool' , None, None, 
                [], [], 
                '''                ''',
                'ignore_leading_space',
                'tailf-aaa', False),
            _MetaInfoClassMember('paginate', ATTRIBUTE, 'bool' , None, None, 
                [], [], 
                '''                ''',
                'paginate',
                'tailf-aaa', False),
            _MetaInfoClassMember('prompt1', ATTRIBUTE, 'str' , None, None, 
                [], [], 
                '''                ''',
                'prompt1',
                'tailf-aaa', False),
            _MetaInfoClassMember('prompt2', ATTRIBUTE, 'str' , None, None, 
                [], [], 
                '''                ''',
                'prompt2',
                'tailf-aaa', False),
            _MetaInfoClassMember('show-defaults', ATTRIBUTE, 'bool' , None, None, 
                [], [], 
                '''                ''',
                'show_defaults',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'session',
            _yang_ns._namespaces['tailf-aaa'],
        'ydk.models.cisco_ios_xe.tailf_aaa'
        ),
    },
    'User.Alias' : {
        'meta_info' : _MetaInfoClass('User.Alias',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str' , None, None, 
                [], [], 
                '''                ''',
                'name',
                'tailf-aaa', True),
            _MetaInfoClassMember('expansion', ATTRIBUTE, 'str' , None, None, 
                [], [], 
                '''                ''',
                'expansion',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'alias',
            _yang_ns._namespaces['tailf-aaa'],
        'ydk.models.cisco_ios_xe.tailf_aaa'
        ),
    },
    'User.Session' : {
        'meta_info' : _MetaInfoClass('User.Session',
            False, 
            [
            _MetaInfoClassMember('autowizard', ATTRIBUTE, 'bool' , None, None, 
                [], [], 
                '''                ''',
                'autowizard',
                'tailf-aaa', False),
            _MetaInfoClassMember('complete-on-space', ATTRIBUTE, 'bool' , None, None, 
                [], [], 
                '''                ''',
                'complete_on_space',
                'tailf-aaa', False),
            _MetaInfoClassMember('display-level', ATTRIBUTE, 'int' , None, None, 
                [('1', '64')], [], 
                '''                ''',
                'display_level',
                'tailf-aaa', False),
            _MetaInfoClassMember('history', ATTRIBUTE, 'int' , None, None, 
                [('0', '8192')], [], 
                '''                ''',
                'history',
                'tailf-aaa', False),
            _MetaInfoClassMember('idle-timeout', ATTRIBUTE, 'int' , None, None, 
                [('0', '8192')], [], 
                '''                ''',
                'idle_timeout',
                'tailf-aaa', False),
            _MetaInfoClassMember('ignore-leading-space', ATTRIBUTE, 'bool' , None, None, 
                [], [], 
                '''                ''',
                'ignore_leading_space',
                'tailf-aaa', False),
            _MetaInfoClassMember('paginate', ATTRIBUTE, 'bool' , None, None, 
                [], [], 
                '''                ''',
                'paginate',
                'tailf-aaa', False),
            _MetaInfoClassMember('prompt1', ATTRIBUTE, 'str' , None, None, 
                [], [], 
                '''                ''',
                'prompt1',
                'tailf-aaa', False),
            _MetaInfoClassMember('prompt2', ATTRIBUTE, 'str' , None, None, 
                [], [], 
                '''                ''',
                'prompt2',
                'tailf-aaa', False),
            _MetaInfoClassMember('show-defaults', ATTRIBUTE, 'bool' , None, None, 
                [], [], 
                '''                ''',
                'show_defaults',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'session',
            _yang_ns._namespaces['tailf-aaa'],
        'ydk.models.cisco_ios_xe.tailf_aaa'
        ),
    },
    'User' : {
        'meta_info' : _MetaInfoClass('User',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str' , None, None, 
                [], [], 
                '''                ''',
                'name',
                'tailf-aaa', True),
            _MetaInfoClassMember('alias', REFERENCE_LIST, 'Alias' , 'ydk.models.cisco_ios_xe.tailf_aaa', 'User.Alias', 
                [], [], 
                '''                ''',
                'alias',
                'tailf-aaa', False),
            _MetaInfoClassMember('description', ATTRIBUTE, 'str' , None, None, 
                [], [], 
                '''                ''',
                'description',
                'tailf-aaa', False),
            _MetaInfoClassMember('session', REFERENCE_CLASS, 'Session' , 'ydk.models.cisco_ios_xe.tailf_aaa', 'User.Session', 
                [], [], 
                '''                ''',
                'session',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'user',
            _yang_ns._namespaces['tailf-aaa'],
        'ydk.models.cisco_ios_xe.tailf_aaa'
        ),
    },
}
_meta_table['Aaa.Authentication.Users.User']['meta_info'].parent =_meta_table['Aaa.Authentication.Users']['meta_info']
_meta_table['Aaa.Authentication.Users']['meta_info'].parent =_meta_table['Aaa.Authentication']['meta_info']
_meta_table['Aaa.Ios.Privilege.Level.Command']['meta_info'].parent =_meta_table['Aaa.Ios.Privilege.Level']['meta_info']
_meta_table['Aaa.Ios.Privilege.Level']['meta_info'].parent =_meta_table['Aaa.Ios.Privilege']['meta_info']
_meta_table['Aaa.Ios.Level']['meta_info'].parent =_meta_table['Aaa.Ios']['meta_info']
_meta_table['Aaa.Ios.Privilege']['meta_info'].parent =_meta_table['Aaa.Ios']['meta_info']
_meta_table['Aaa.Authentication']['meta_info'].parent =_meta_table['Aaa']['meta_info']
_meta_table['Aaa.Ios']['meta_info'].parent =_meta_table['Aaa']['meta_info']
_meta_table['User.Alias']['meta_info'].parent =_meta_table['User']['meta_info']
_meta_table['User.Session']['meta_info'].parent =_meta_table['User']['meta_info']
