


import re
import collections

from enum import Enum

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum, _dm_validate_value
from ydk.types import Empty, YList, DELETE, Decimal64, FixedBitsDict
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_CLASS, REFERENCE_LIST, REFERENCE_LEAFLIST,     REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, REFERENCE_BITS, REFERENCE_UNION

from ydk.errors import YPYError, YPYDataValidationError
from ydk.models import _yang_ns

_meta_table = {
    'CFWUrlServerStatus_Enum' : _MetaInfoEnum('CFWUrlServerStatus_Enum', 'ydk.models.firewall.CISCO_FIREWALL_TC',
        {
            'online':'ONLINE',
            'offline':'OFFLINE',
            'indeterminate':'INDETERMINATE',
        }, 'CISCO-FIREWALL-TC', _yang_ns._namespaces['CISCO-FIREWALL-TC']),
    'CFWNetworkProtocol_Enum' : _MetaInfoEnum('CFWNetworkProtocol_Enum', 'ydk.models.firewall.CISCO_FIREWALL_TC',
        {
            'none':'NONE',
            'other':'OTHER',
            'ip':'IP',
            'icmp':'ICMP',
            'gre':'GRE',
            'udp':'UDP',
            'tcp':'TCP',
        }, 'CISCO-FIREWALL-TC', _yang_ns._namespaces['CISCO-FIREWALL-TC']),
    'CFWUrlfVendorId_Enum' : _MetaInfoEnum('CFWUrlfVendorId_Enum', 'ydk.models.firewall.CISCO_FIREWALL_TC',
        {
            'other':'OTHER',
            'websense':'WEBSENSE',
            'n2h2':'N2H2',
        }, 'CISCO-FIREWALL-TC', _yang_ns._namespaces['CISCO-FIREWALL-TC']),
    'CFWApplicationProtocol_Enum' : _MetaInfoEnum('CFWApplicationProtocol_Enum', 'ydk.models.firewall.CISCO_FIREWALL_TC',
        {
            'none':'NONE',
            'other':'OTHER',
            'ftp':'FTP',
            'telnet':'TELNET',
            'smtp':'SMTP',
            'http':'HTTP',
            'tacacs':'TACACS',
            'dns':'DNS',
            'sqlnet':'SQLNET',
            'https':'HTTPS',
            'tftp':'TFTP',
            'gopher':'GOPHER',
            'finger':'FINGER',
            'kerberos':'KERBEROS',
            'pop2':'POP2',
            'pop3':'POP3',
            'sunRpc':'SUNRPC',
            'msRpc':'MSRPC',
            'nntp':'NNTP',
            'snmp':'SNMP',
            'imap':'IMAP',
            'ldap':'LDAP',
            'exec':'EXEC',
            'login':'LOGIN',
            'shell':'SHELL',
            'msSql':'MSSQL',
            'sybaseSql':'SYBASESQL',
            'nfs':'NFS',
            'lotusnote':'LOTUSNOTE',
            'h323':'H323',
            'cuseeme':'CUSEEME',
            'realmedia':'REALMEDIA',
            'netshow':'NETSHOW',
            'streamworks':'STREAMWORKS',
            'vdolive':'VDOLIVE',
            'sap':'SAP',
            'sip':'SIP',
            'mgcp':'MGCP',
            'rtsp':'RTSP',
            'skinny':'SKINNY',
            'gtpV0':'GTPV0',
            'gtpV1':'GTPV1',
            'echo':'ECHO',
            'discard':'DISCARD',
            'daytime':'DAYTIME',
            'netstat':'NETSTAT',
            'ssh':'SSH',
            'time':'TIME',
            'tacacsDs':'TACACSDS',
            'bootps':'BOOTPS',
            'bootpc':'BOOTPC',
            'dnsix':'DNSIX',
            'rtelnet':'RTELNET',
            'ident':'IDENT',
            'sqlServ':'SQLSERV',
            'ntp':'NTP',
            'pwdgen':'PWDGEN',
            'ciscoFna':'CISCOFNA',
            'ciscoTna':'CISCOTNA',
            'ciscoSys':'CISCOSYS',
            'netbiosNs':'NETBIOSNS',
            'netbiosDgm':'NETBIOSDGM',
            'netbiosSsn':'NETBIOSSSN',
            'sqlSrv':'SQLSRV',
            'snmpTrap':'SNMPTRAP',
            'rsvd':'RSVD',
            'send':'SEND',
            'xdmcp':'XDMCP',
            'bgp':'BGP',
            'irc':'IRC',
            'qmtp':'QMTP',
            'ipx':'IPX',
            'dbase':'DBASE',
            'imap3':'IMAP3',
            'rsvpTunnel':'RSVPTUNNEL',
            'hpCollector':'HPCOLLECTOR',
            'hpManagedNode':'HPMANAGEDNODE',
            'hpAlarmMgr':'HPALARMMGR',
            'microsoftDs':'MICROSOFTDS',
            'creativeServer':'CREATIVESERVER',
            'creativePartnr':'CREATIVEPARTNR',
            'appleQtc':'APPLEQTC',
            'igmpV3Lite':'IGMPV3LITE',
            'isakmp':'ISAKMP',
            'biff':'BIFF',
            'who':'WHO',
            'syslog':'SYSLOG',
            'router':'ROUTER',
            'ncp':'NCP',
            'timed':'TIMED',
            'ircServ':'IRCSERV',
            'uucp':'UUCP',
            'syslogConn':'SYSLOGCONN',
            'sshell':'SSHELL',
            'ldaps':'LDAPS',
            'dhcpFailover':'DHCPFAILOVER',
            'msexchRouting':'MSEXCHROUTING',
            'entrustSvcs':'ENTRUSTSVCS',
            'entrustSvcHandler':'ENTRUSTSVCHANDLER',
            'ciscoTdp':'CISCOTDP',
            'webster':'WEBSTER',
            'gdoi':'GDOI',
            'iscsi':'ISCSI',
            'cddbp':'CDDBP',
            'ftps':'FTPS',
            'telnets':'TELNETS',
            'imaps':'IMAPS',
            'ircs':'IRCS',
            'pop3s':'POP3S',
            'socks':'SOCKS',
            'kazaa':'KAZAA',
            'msSqlM':'MSSQLM',
            'msSna':'MSSNA',
            'wins':'WINS',
            'ica':'ICA',
            'orasrv':'ORASRV',
            'rdbDbsDisp':'RDBDBSDISP',
            'vqp':'VQP',
            'icabrowser':'ICABROWSER',
            'kermit':'KERMIT',
            'rsvpEncap':'RSVPENCAP',
            'l2tp':'L2TP',
            'pptp':'PPTP',
            'h323Gatestat':'H323GATESTAT',
            'rWinsock':'RWINSOCK',
            'radius':'RADIUS',
            'hsrp':'HSRP',
            'net8Cman':'NET8CMAN',
            'oracleEmVp':'ORACLEEMVP',
            'oracleNames':'ORACLENAMES',
            'oracle':'ORACLE',
            'ciscoSvcs':'CISCOSVCS',
            'ciscoNetMgmt':'CISCONETMGMT',
            'stun':'STUN',
            'trRsrb':'TRRSRB',
            'ddnsV3':'DDNSV3',
            'aceSvr':'ACESVR',
            'giop':'GIOP',
            'ttc':'TTC',
            'ipass':'IPASS',
            'clp':'CLP',
            'citrixImaClient':'CITRIXIMACLIENT',
            'sms':'SMS',
            'citrix':'CITRIX',
            'realSecure':'REALSECURE',
            'lotusMtap':'LOTUSMTAP',
            'cifs':'CIFS',
            'msDotnetster':'MSDOTNETSTER',
            'tarantella':'TARANTELLA',
            'fcipPort':'FCIPPORT',
            'ssp':'SSP',
            'iscsiTarget':'ISCSITARGET',
            'mySql':'MYSQL',
            'msClusterNet':'MSCLUSTERNET',
            'ldapAdmin':'LDAPADMIN',
            'ieee80211Iapp':'IEEE80211IAPP',
            'oemAgent':'OEMAGENT',
            'rtcPmPort':'RTCPMPORT',
            'dbControlAgent':'DBCONTROLAGENT',
            'ipsecMsft':'IPSECMSFT',
            'sipTls':'SIPTLS',
            'aim':'AIM',
            'pcAnyWhereData':'PCANYWHEREDATA',
            'pcAnyWhereStat':'PCANYWHERESTAT',
            'x11':'X11',
            'ircu':'IRCU',
            'n2h2Server':'N2H2SERVER',
            'h323CallSigAlt':'H323CALLSIGALT',
            'yahooMsgr':'YAHOOMSGR',
            'msnMsgr':'MSNMSGR',
        }, 'CISCO-FIREWALL-TC', _yang_ns._namespaces['CISCO-FIREWALL-TC']),
    'CFWPolicyTargetType_Enum' : _MetaInfoEnum('CFWPolicyTargetType_Enum', 'ydk.models.firewall.CISCO_FIREWALL_TC',
        {
            'all':'ALL',
            'other':'OTHER',
            'interface':'INTERFACE',
            'zone':'ZONE',
            'zonepair':'ZONEPAIR',
            'user':'USER',
            'usergroup':'USERGROUP',
            'context':'CONTEXT',
        }, 'CISCO-FIREWALL-TC', _yang_ns._namespaces['CISCO-FIREWALL-TC']),
}
