""" CISCO_ENTITY_ALARM_MIB 

This MIB module defines the managed objects that support the
monitoring of alarms generated by physical entities contained
by the system, including chassis, slots, modules, ports, power
supplies, and fans.  In order to monitor alarms generated by a
physical entity, it must be represented by a row in the
entPhysicalTable (see ENTITY\-MIB).

"""


import re
import collections

from enum import Enum

from ydk.types import Empty, YList, YLeafList, DELETE, Decimal64, FixedBitsDict

from ydk.errors import YPYError, YPYModelError



class AlarmseverityEnum(Enum):
    """
    AlarmseverityEnum

    Each alarm type defined by a vendor type employed by the

    system has an associated severity.  Bellcore TR\-NWT\-000474

    defines these severities as follows\:

    'critical'  An alarm used to indicate a severe, service\-

                affecting condition has occurred and that immediate

                corrective action is imperative, regardless of the

                time of day or day of the week.

    'major'     An alarm used for hardware or software conditions

                that indicate a serious disruption of service or the

                malfunctioning or failure of important hardware.

                These troubles require the immediate attention and

                response of a technician to restore or maintain

                system capability.  The urgency is less than in

                critical situations because of a lesser immediate

                or impending effect on service or system

                performance.

    'minor'     An alarm used for troubles that do not have a

                serious effect on service to customers or for

                troubles in hardware that are not essential to

                the operation of the system.

    'info'      An indication used to raise attention to a condition

                that could possibly be an impending problem or to 

                notify the customer of an event that improves

                operation.

    .. data:: critical = 1

    .. data:: major = 2

    .. data:: minor = 3

    .. data:: info = 4

    """

    critical = 1

    major = 2

    minor = 3

    info = 4


    @staticmethod
    def _meta_info():
        from ydk.models.cisco_ios_xe._meta import _CISCO_ENTITY_ALARM_MIB as meta
        return meta._meta_table['AlarmseverityEnum']



class CiscoEntityAlarmMib(object):
    """
    
    
    .. attribute:: cealarmdescrmaptable
    
    	For each type of entity (represented entPhysicalVendorType OID), this table contains a mapping between a unique  ceAlarmDescrIndex and entPhysicalvendorType OID
    	**type**\:   :py:class:`Cealarmdescrmaptable <ydk.models.cisco_ios_xe.CISCO_ENTITY_ALARM_MIB.CiscoEntityAlarmMib.Cealarmdescrmaptable>`
    
    .. attribute:: cealarmdescrtable
    
    	This table contains a description for each alarm type defined by each vendor type employed by the system. Observe that this table is sparse in nature, as it is rarely the case that a physical entity type needs to  define every alarm in its alarm space
    	**type**\:   :py:class:`Cealarmdescrtable <ydk.models.cisco_ios_xe.CISCO_ENTITY_ALARM_MIB.CiscoEntityAlarmMib.Cealarmdescrtable>`
    
    .. attribute:: cealarmfiltering
    
    	
    	**type**\:   :py:class:`Cealarmfiltering <ydk.models.cisco_ios_xe.CISCO_ENTITY_ALARM_MIB.CiscoEntityAlarmMib.Cealarmfiltering>`
    
    .. attribute:: cealarmfilterprofiletable
    
    	This table contains a list of alarm filter profiles
    	**type**\:   :py:class:`Cealarmfilterprofiletable <ydk.models.cisco_ios_xe.CISCO_ENTITY_ALARM_MIB.CiscoEntityAlarmMib.Cealarmfilterprofiletable>`
    
    .. attribute:: cealarmhistory
    
    	
    	**type**\:   :py:class:`Cealarmhistory <ydk.models.cisco_ios_xe.CISCO_ENTITY_ALARM_MIB.CiscoEntityAlarmMib.Cealarmhistory>`
    
    .. attribute:: cealarmhisttable
    
    	This table contains a history of ceAlarmIndicate and ceAlarmClear traps generated by the agent
    	**type**\:   :py:class:`Cealarmhisttable <ydk.models.cisco_ios_xe.CISCO_ENTITY_ALARM_MIB.CiscoEntityAlarmMib.Cealarmhisttable>`
    
    .. attribute:: cealarmmonitoring
    
    	
    	**type**\:   :py:class:`Cealarmmonitoring <ydk.models.cisco_ios_xe.CISCO_ENTITY_ALARM_MIB.CiscoEntityAlarmMib.Cealarmmonitoring>`
    
    .. attribute:: cealarmtable
    
    	This table specifies alarm control and status information related to each physical entity contained by the system, including the alarms currently being asserted by each physical entity capable of generating alarms
    	**type**\:   :py:class:`Cealarmtable <ydk.models.cisco_ios_xe.CISCO_ENTITY_ALARM_MIB.CiscoEntityAlarmMib.Cealarmtable>`
    
    

    """

    _prefix = 'CISCO-ENTITY-ALARM-MIB'
    _revision = '1999-07-06'

    def __init__(self):
        self.cealarmdescrmaptable = CiscoEntityAlarmMib.Cealarmdescrmaptable()
        self.cealarmdescrmaptable.parent = self
        self.cealarmdescrtable = CiscoEntityAlarmMib.Cealarmdescrtable()
        self.cealarmdescrtable.parent = self
        self.cealarmfiltering = CiscoEntityAlarmMib.Cealarmfiltering()
        self.cealarmfiltering.parent = self
        self.cealarmfilterprofiletable = CiscoEntityAlarmMib.Cealarmfilterprofiletable()
        self.cealarmfilterprofiletable.parent = self
        self.cealarmhistory = CiscoEntityAlarmMib.Cealarmhistory()
        self.cealarmhistory.parent = self
        self.cealarmhisttable = CiscoEntityAlarmMib.Cealarmhisttable()
        self.cealarmhisttable.parent = self
        self.cealarmmonitoring = CiscoEntityAlarmMib.Cealarmmonitoring()
        self.cealarmmonitoring.parent = self
        self.cealarmtable = CiscoEntityAlarmMib.Cealarmtable()
        self.cealarmtable.parent = self


    class Cealarmmonitoring(object):
        """
        
        
        .. attribute:: cealarmcriticalcount
        
        	The value of this object specifies the number of alarms currently asserted with a severity of 'critical'
        	**type**\:  int
        
        	**range:** 0..4294967295
        
        .. attribute:: cealarmcutoff
        
        	If the management client writes a value of 'true' to this object, the agent stops signalling all external audible alarms under the control of the agent.  Reading this object should always result in a value of 'false'.  Observe that alarm cutoff does not have an effect on monitoring, history logging, generation of notifications, or syslog message generation.  It also does not prevent the agent from signalling external audible alarms for alarms asserted after alarm\-cutoff.  This object emulates the 'alarm cut\-off' mechanism typically installed in a central office (e.g., a big red button).  Observe this object should neither affect external visual alarms under the control of the agent, nor should it affect the current state of alarms being asserted by the system
        	**type**\:  bool
        
        .. attribute:: cealarmmajorcount
        
        	The value of this object specifies the number of alarms currently asserted with a severity of 'major'
        	**type**\:  int
        
        	**range:** 0..4294967295
        
        .. attribute:: cealarmminorcount
        
        	The value of this object specifies the number of alarms currently asserted with a severity of 'minor'
        	**type**\:  int
        
        	**range:** 0..4294967295
        
        

        """

        _prefix = 'CISCO-ENTITY-ALARM-MIB'
        _revision = '1999-07-06'

        def __init__(self):
            self.parent = None
            self.cealarmcriticalcount = None
            self.cealarmcutoff = None
            self.cealarmmajorcount = None
            self.cealarmminorcount = None

        @property
        def _common_path(self):

            return '/CISCO-ENTITY-ALARM-MIB:CISCO-ENTITY-ALARM-MIB/CISCO-ENTITY-ALARM-MIB:ceAlarmMonitoring'

        def is_config(self):
            ''' Returns True if this instance represents config data else returns False '''
            return False

        def _has_data(self):
            if self.cealarmcriticalcount is not None:
                return True

            if self.cealarmcutoff is not None:
                return True

            if self.cealarmmajorcount is not None:
                return True

            if self.cealarmminorcount is not None:
                return True

            return False

        @staticmethod
        def _meta_info():
            from ydk.models.cisco_ios_xe._meta import _CISCO_ENTITY_ALARM_MIB as meta
            return meta._meta_table['CiscoEntityAlarmMib.Cealarmmonitoring']['meta_info']


    class Cealarmhistory(object):
        """
        
        
        .. attribute:: cealarmhistlastindex
        
        	This object specifies the value of the ceAlarmHistIndex object corresponding to the last entry added to the table by the agent.  If the management client uses the notifications defined by this module, then it can poll this object to determine whether it has missed a notification sent by the agent
        	**type**\:  int
        
        	**range:** 0..4294967295
        
        .. attribute:: cealarmhisttablesize
        
        	This object specifies the number of entries that the  ceAlarmHistTable can contain.  When a physical entity generates an unfiltered alarm, and the capacity of the ceAlarmHistTable has reached the value specified by this object, then the agent deletes the oldest entity in order to accommodate the new entry. A value of '0' prevents any history from being retained.  
        	**type**\:  int
        
        	**range:** 0..500
        
        

        """

        _prefix = 'CISCO-ENTITY-ALARM-MIB'
        _revision = '1999-07-06'

        def __init__(self):
            self.parent = None
            self.cealarmhistlastindex = None
            self.cealarmhisttablesize = None

        @property
        def _common_path(self):

            return '/CISCO-ENTITY-ALARM-MIB:CISCO-ENTITY-ALARM-MIB/CISCO-ENTITY-ALARM-MIB:ceAlarmHistory'

        def is_config(self):
            ''' Returns True if this instance represents config data else returns False '''
            return False

        def _has_data(self):
            if self.cealarmhistlastindex is not None:
                return True

            if self.cealarmhisttablesize is not None:
                return True

            return False

        @staticmethod
        def _meta_info():
            from ydk.models.cisco_ios_xe._meta import _CISCO_ENTITY_ALARM_MIB as meta
            return meta._meta_table['CiscoEntityAlarmMib.Cealarmhistory']['meta_info']


    class Cealarmfiltering(object):
        """
        
        
        .. attribute:: cealarmfilterprofileindexnext
        
        	This object contains an appropriate value to be used for ceAlarmFilterIndex when creating entries in the ceAlarmFilterProfileTable.  The value '0' indicates that no unassigned entries are available.  To obtain a ceAlarmFilterIndex, the management client issues a get request.  The agent has the responsibility of  modifying the value of this object following each  successful get request
        	**type**\:  int
        
        	**range:** 0..4294967295
        
        .. attribute:: cealarmnotifiesenable
        
        	This object specifies a severity threshold governing the generation of ceAlarmAsserted and ceAlarmCleared notifications.  For example, if the value of this object is set to 'major', then the agent generates these notifications if and only if the severity of the alarm being indicated is 'major' or 'critical'.  The value of '0' disables the  generation of notifications.  Observe that this setting overrides the value of the  ceAlarmFilterNotifiesEnabled object.  This object affects notification generation only; that is, it does not affect monitoring, history logging, and syslog message generation
        	**type**\:  int
        
        	**range:** 0..4
        
        .. attribute:: cealarmsyslogenable
        
        	This object specifies a severity threshold governing the generation of syslog messages corresponding to alarms.  For example, if the value of this object is set to 'major', then the agent generates these a syslog message if and only if the severity of the alarm being indicated is 'major' or 'critical'. The value of '0' disables the generation of syslog messages corresponding to alarms.  Observe that this setting overrides the value of the  ceAlarmFilterSyslogEnabled object.  This object affects syslog message generation only; that is, it does not have an effect on monitoring, history logging, and generation of notifications
        	**type**\:  int
        
        	**range:** 0..4
        
        

        """

        _prefix = 'CISCO-ENTITY-ALARM-MIB'
        _revision = '1999-07-06'

        def __init__(self):
            self.parent = None
            self.cealarmfilterprofileindexnext = None
            self.cealarmnotifiesenable = None
            self.cealarmsyslogenable = None

        @property
        def _common_path(self):

            return '/CISCO-ENTITY-ALARM-MIB:CISCO-ENTITY-ALARM-MIB/CISCO-ENTITY-ALARM-MIB:ceAlarmFiltering'

        def is_config(self):
            ''' Returns True if this instance represents config data else returns False '''
            return False

        def _has_data(self):
            if self.cealarmfilterprofileindexnext is not None:
                return True

            if self.cealarmnotifiesenable is not None:
                return True

            if self.cealarmsyslogenable is not None:
                return True

            return False

        @staticmethod
        def _meta_info():
            from ydk.models.cisco_ios_xe._meta import _CISCO_ENTITY_ALARM_MIB as meta
            return meta._meta_table['CiscoEntityAlarmMib.Cealarmfiltering']['meta_info']


    class Cealarmdescrmaptable(object):
        """
        For each type of entity (represented entPhysicalVendorType
        OID), this table contains a mapping between a unique 
        ceAlarmDescrIndex and entPhysicalvendorType OID.
        
        .. attribute:: cealarmdescrmapentry
        
        	A mapping between an alarm description and a vendor type
        	**type**\: list of    :py:class:`Cealarmdescrmapentry <ydk.models.cisco_ios_xe.CISCO_ENTITY_ALARM_MIB.CiscoEntityAlarmMib.Cealarmdescrmaptable.Cealarmdescrmapentry>`
        
        

        """

        _prefix = 'CISCO-ENTITY-ALARM-MIB'
        _revision = '1999-07-06'

        def __init__(self):
            self.parent = None
            self.cealarmdescrmapentry = YList()
            self.cealarmdescrmapentry.parent = self
            self.cealarmdescrmapentry.name = 'cealarmdescrmapentry'


        class Cealarmdescrmapentry(object):
            """
            A mapping between an alarm description and a vendor type.
            
            .. attribute:: cealarmdescrindex  <key>
            
            	This object uniquely identifies an alarm description
            	**type**\:  int
            
            	**range:** 0..4294967295
            
            .. attribute:: cealarmdescrvendortype
            
            	This object specifies an object identifier (typically an enterprise\-specific OID) that uniquely identifies the vendor type of those physical entities that this alarm description applies to
            	**type**\:  str
            
            	**pattern:** (([0\-1](\\.[1\-3]?[0\-9]))\|(2\\.(0\|([1\-9]\\d\*))))(\\.(0\|([1\-9]\\d\*)))\*
            
            

            """

            _prefix = 'CISCO-ENTITY-ALARM-MIB'
            _revision = '1999-07-06'

            def __init__(self):
                self.parent = None
                self.cealarmdescrindex = None
                self.cealarmdescrvendortype = None

            @property
            def _common_path(self):
                if self.cealarmdescrindex is None:
                    raise YPYModelError('Key property cealarmdescrindex is None')

                return '/CISCO-ENTITY-ALARM-MIB:CISCO-ENTITY-ALARM-MIB/CISCO-ENTITY-ALARM-MIB:ceAlarmDescrMapTable/CISCO-ENTITY-ALARM-MIB:ceAlarmDescrMapEntry[CISCO-ENTITY-ALARM-MIB:ceAlarmDescrIndex = ' + str(self.cealarmdescrindex) + ']'

            def is_config(self):
                ''' Returns True if this instance represents config data else returns False '''
                return False

            def _has_data(self):
                if self.cealarmdescrindex is not None:
                    return True

                if self.cealarmdescrvendortype is not None:
                    return True

                return False

            @staticmethod
            def _meta_info():
                from ydk.models.cisco_ios_xe._meta import _CISCO_ENTITY_ALARM_MIB as meta
                return meta._meta_table['CiscoEntityAlarmMib.Cealarmdescrmaptable.Cealarmdescrmapentry']['meta_info']

        @property
        def _common_path(self):

            return '/CISCO-ENTITY-ALARM-MIB:CISCO-ENTITY-ALARM-MIB/CISCO-ENTITY-ALARM-MIB:ceAlarmDescrMapTable'

        def is_config(self):
            ''' Returns True if this instance represents config data else returns False '''
            return False

        def _has_data(self):
            if self.cealarmdescrmapentry is not None:
                for child_ref in self.cealarmdescrmapentry:
                    if child_ref._has_data():
                        return True

            return False

        @staticmethod
        def _meta_info():
            from ydk.models.cisco_ios_xe._meta import _CISCO_ENTITY_ALARM_MIB as meta
            return meta._meta_table['CiscoEntityAlarmMib.Cealarmdescrmaptable']['meta_info']


    class Cealarmdescrtable(object):
        """
        This table contains a description for each alarm type
        defined by each vendor type employed by the system.
        Observe that this table is sparse in nature, as it is
        rarely the case that a physical entity type needs to 
        define every alarm in its alarm space.
        
        .. attribute:: cealarmdescrentry
        
        	A collection of attributes that describe an alarm type
        	**type**\: list of    :py:class:`Cealarmdescrentry <ydk.models.cisco_ios_xe.CISCO_ENTITY_ALARM_MIB.CiscoEntityAlarmMib.Cealarmdescrtable.Cealarmdescrentry>`
        
        

        """

        _prefix = 'CISCO-ENTITY-ALARM-MIB'
        _revision = '1999-07-06'

        def __init__(self):
            self.parent = None
            self.cealarmdescrentry = YList()
            self.cealarmdescrentry.parent = self
            self.cealarmdescrentry.name = 'cealarmdescrentry'


        class Cealarmdescrentry(object):
            """
            A collection of attributes that describe an alarm type.
            
            .. attribute:: cealarmdescrindex  <key>
            
            	
            	**type**\:  int
            
            	**range:** 0..4294967295
            
            	**refers to**\:  :py:class:`cealarmdescrindex <ydk.models.cisco_ios_xe.CISCO_ENTITY_ALARM_MIB.CiscoEntityAlarmMib.Cealarmdescrmaptable.Cealarmdescrmapentry>`
            
            .. attribute:: cealarmdescralarmtype  <key>
            
            	This object specifies the alarm type being described
            	**type**\:  int
            
            	**range:** 0..255
            
            .. attribute:: cealarmdescrseverity
            
            	This object specifies the severity associated with the alarm type.  An implementation may chose to not allow dynamic severity assignment, in which case it would restrict access to this object to be read\-only.  If an implementation allows dynamic severity assignment, then a management client can revert to the default severity by writing the value '0' to this object.  There exists a class of systems that should implement dynamic severity assignment.  For example, consider a DSLAM (Digital Subscriber Loop Access Multiplexor) designed for both the central office and pedestal environments.  A 'pedestal' is typically a dark\-green metal box mounted on a concrete or stone foundation in which carrier\-class companies house equipment. The central office typically controls the temperature and humidity of the environment, reducing reliance on a system's fans.  Thus, the customer probably has a desire to reduce the  severity of alarms indicating the failure of a fan.  However, a pedestal environment has a much greater reliance on a system's fans.  Thus, the customer probably has a desire to increase the severity of alarms indicating the failure of a fan
            	**type**\:  int
            
            	**range:** 0..4
            
            .. attribute:: cealarmdescrtext
            
            	This object specifies a human\-readable message describing the alarm
            	**type**\:  str
            
            

            """

            _prefix = 'CISCO-ENTITY-ALARM-MIB'
            _revision = '1999-07-06'

            def __init__(self):
                self.parent = None
                self.cealarmdescrindex = None
                self.cealarmdescralarmtype = None
                self.cealarmdescrseverity = None
                self.cealarmdescrtext = None

            @property
            def _common_path(self):
                if self.cealarmdescrindex is None:
                    raise YPYModelError('Key property cealarmdescrindex is None')
                if self.cealarmdescralarmtype is None:
                    raise YPYModelError('Key property cealarmdescralarmtype is None')

                return '/CISCO-ENTITY-ALARM-MIB:CISCO-ENTITY-ALARM-MIB/CISCO-ENTITY-ALARM-MIB:ceAlarmDescrTable/CISCO-ENTITY-ALARM-MIB:ceAlarmDescrEntry[CISCO-ENTITY-ALARM-MIB:ceAlarmDescrIndex = ' + str(self.cealarmdescrindex) + '][CISCO-ENTITY-ALARM-MIB:ceAlarmDescrAlarmType = ' + str(self.cealarmdescralarmtype) + ']'

            def is_config(self):
                ''' Returns True if this instance represents config data else returns False '''
                return False

            def _has_data(self):
                if self.cealarmdescrindex is not None:
                    return True

                if self.cealarmdescralarmtype is not None:
                    return True

                if self.cealarmdescrseverity is not None:
                    return True

                if self.cealarmdescrtext is not None:
                    return True

                return False

            @staticmethod
            def _meta_info():
                from ydk.models.cisco_ios_xe._meta import _CISCO_ENTITY_ALARM_MIB as meta
                return meta._meta_table['CiscoEntityAlarmMib.Cealarmdescrtable.Cealarmdescrentry']['meta_info']

        @property
        def _common_path(self):

            return '/CISCO-ENTITY-ALARM-MIB:CISCO-ENTITY-ALARM-MIB/CISCO-ENTITY-ALARM-MIB:ceAlarmDescrTable'

        def is_config(self):
            ''' Returns True if this instance represents config data else returns False '''
            return False

        def _has_data(self):
            if self.cealarmdescrentry is not None:
                for child_ref in self.cealarmdescrentry:
                    if child_ref._has_data():
                        return True

            return False

        @staticmethod
        def _meta_info():
            from ydk.models.cisco_ios_xe._meta import _CISCO_ENTITY_ALARM_MIB as meta
            return meta._meta_table['CiscoEntityAlarmMib.Cealarmdescrtable']['meta_info']


    class Cealarmtable(object):
        """
        This table specifies alarm control and status information
        related to each physical entity contained by the system,
        including the alarms currently being asserted by each physical
        entity capable of generating alarms.
        
        .. attribute:: cealarmentry
        
        	Alarm control and status information related to the  corresponding physical entity, including a list of those alarms currently being asserted by that physical entity
        	**type**\: list of    :py:class:`Cealarmentry <ydk.models.cisco_ios_xe.CISCO_ENTITY_ALARM_MIB.CiscoEntityAlarmMib.Cealarmtable.Cealarmentry>`
        
        

        """

        _prefix = 'CISCO-ENTITY-ALARM-MIB'
        _revision = '1999-07-06'

        def __init__(self):
            self.parent = None
            self.cealarmentry = YList()
            self.cealarmentry.parent = self
            self.cealarmentry.name = 'cealarmentry'


        class Cealarmentry(object):
            """
            Alarm control and status information related to the 
            corresponding physical entity, including a list of those
            alarms currently being asserted by that physical entity.
            
            .. attribute:: entphysicalindex  <key>
            
            	
            	**type**\:  int
            
            	**range:** 1..2147483647
            
            	**refers to**\:  :py:class:`entphysicalindex <ydk.models.cisco_ios_xe.ENTITY_MIB.EntityMib.Entphysicaltable.Entphysicalentry>`
            
            .. attribute:: cealarmfilterprofile
            
            	This object specifies the alarm filter profile associated with the corresponding physical entity.  An alarm filter profile controls which alarm types the agent will monitor and signal for the corresponding physical entity.  If the value of this object is '0', then the agent monitors and signals all alarms associated with the corresponding physical entity
            	**type**\:  int
            
            	**range:** 0..4294967295
            
            .. attribute:: cealarmlist
            
            	This object specifies those alarms currently being asserted by the corresponding physical entity.  Note, an alarm indicates a condition, not an event.  An alarm has two states\:      'asserted'  Indicates that the condition described by the                 alarm exists.      'cleared'   Indicates that the condition described by the                 alarm does not exist.  For example, a slot in a chassis may define an alarm that specifies whether the slot contains a module.  At the time of module insertion, the physical entity corresponding to the slot asserts this alarm, and the alarm remains asserted until the  slot becomes empty.  If an alarm is being asserted by the physical entity, then the corresponding bit in the alarm list is set to a one. Observe that if the physical entity is not currently asserting any alarms, then the list will have a length of zero
            	**type**\:  str
            
            	**length:** 0..32
            
            .. attribute:: cealarmseverity
            
            	This object specifies the highest severity alarm currently being asserted by the corresponding physical entity.  A value of '0' indicates that there the corresponding physical entity currently is not asserting any alarms
            	**type**\:  int
            
            	**range:** 0..4
            
            

            """

            _prefix = 'CISCO-ENTITY-ALARM-MIB'
            _revision = '1999-07-06'

            def __init__(self):
                self.parent = None
                self.entphysicalindex = None
                self.cealarmfilterprofile = None
                self.cealarmlist = None
                self.cealarmseverity = None

            @property
            def _common_path(self):
                if self.entphysicalindex is None:
                    raise YPYModelError('Key property entphysicalindex is None')

                return '/CISCO-ENTITY-ALARM-MIB:CISCO-ENTITY-ALARM-MIB/CISCO-ENTITY-ALARM-MIB:ceAlarmTable/CISCO-ENTITY-ALARM-MIB:ceAlarmEntry[CISCO-ENTITY-ALARM-MIB:entPhysicalIndex = ' + str(self.entphysicalindex) + ']'

            def is_config(self):
                ''' Returns True if this instance represents config data else returns False '''
                return False

            def _has_data(self):
                if self.entphysicalindex is not None:
                    return True

                if self.cealarmfilterprofile is not None:
                    return True

                if self.cealarmlist is not None:
                    return True

                if self.cealarmseverity is not None:
                    return True

                return False

            @staticmethod
            def _meta_info():
                from ydk.models.cisco_ios_xe._meta import _CISCO_ENTITY_ALARM_MIB as meta
                return meta._meta_table['CiscoEntityAlarmMib.Cealarmtable.Cealarmentry']['meta_info']

        @property
        def _common_path(self):

            return '/CISCO-ENTITY-ALARM-MIB:CISCO-ENTITY-ALARM-MIB/CISCO-ENTITY-ALARM-MIB:ceAlarmTable'

        def is_config(self):
            ''' Returns True if this instance represents config data else returns False '''
            return False

        def _has_data(self):
            if self.cealarmentry is not None:
                for child_ref in self.cealarmentry:
                    if child_ref._has_data():
                        return True

            return False

        @staticmethod
        def _meta_info():
            from ydk.models.cisco_ios_xe._meta import _CISCO_ENTITY_ALARM_MIB as meta
            return meta._meta_table['CiscoEntityAlarmMib.Cealarmtable']['meta_info']


    class Cealarmhisttable(object):
        """
        This table contains a history of ceAlarmIndicate and
        ceAlarmClear traps generated by the agent.
        
        .. attribute:: cealarmhistentry
        
        	The information conveyed by a ceAlarmIndicate or ceAlarmClear trap
        	**type**\: list of    :py:class:`Cealarmhistentry <ydk.models.cisco_ios_xe.CISCO_ENTITY_ALARM_MIB.CiscoEntityAlarmMib.Cealarmhisttable.Cealarmhistentry>`
        
        

        """

        _prefix = 'CISCO-ENTITY-ALARM-MIB'
        _revision = '1999-07-06'

        def __init__(self):
            self.parent = None
            self.cealarmhistentry = YList()
            self.cealarmhistentry.parent = self
            self.cealarmhistentry.name = 'cealarmhistentry'


        class Cealarmhistentry(object):
            """
            The information conveyed by a ceAlarmIndicate or
            ceAlarmClear trap.
            
            .. attribute:: cealarmhistindex  <key>
            
            	An integer value uniquely identifying the entry in the table. The value of this object starts at '1' and monotonically increases for each alarm condition transition monitored by the agent.  If the value of this object is '4294967295', the agent will reset it to '1' upon monitoring the next alarm condition transition
            	**type**\:  int
            
            	**range:** 0..4294967295
            
            .. attribute:: cealarmhistalarmtype
            
            	This object specifies the type of alarm generated
            	**type**\:  int
            
            	**range:** 0..255
            
            .. attribute:: cealarmhistentphysicalindex
            
            	This object specifies the physical entity that generated the alarm
            	**type**\:  int
            
            	**range:** 1..2147483647
            
            .. attribute:: cealarmhistseverity
            
            	This object specifies the severity of the alarm generated
            	**type**\:   :py:class:`AlarmseverityEnum <ydk.models.cisco_ios_xe.CISCO_ENTITY_ALARM_MIB.AlarmseverityEnum>`
            
            .. attribute:: cealarmhisttimestamp
            
            	This object specifies the value of the sysUpTime object at the time the alarm was generated
            	**type**\:  int
            
            	**range:** 0..4294967295
            
            .. attribute:: cealarmhisttype
            
            	This object specifies whether the agent created the entry as the result of an alarm being asserted or cleared
            	**type**\:   :py:class:`CealarmhisttypeEnum <ydk.models.cisco_ios_xe.CISCO_ENTITY_ALARM_MIB.CiscoEntityAlarmMib.Cealarmhisttable.Cealarmhistentry.CealarmhisttypeEnum>`
            
            

            """

            _prefix = 'CISCO-ENTITY-ALARM-MIB'
            _revision = '1999-07-06'

            def __init__(self):
                self.parent = None
                self.cealarmhistindex = None
                self.cealarmhistalarmtype = None
                self.cealarmhistentphysicalindex = None
                self.cealarmhistseverity = None
                self.cealarmhisttimestamp = None
                self.cealarmhisttype = None

            class CealarmhisttypeEnum(Enum):
                """
                CealarmhisttypeEnum

                This object specifies whether the agent created the entry as

                the result of an alarm being asserted or cleared.

                .. data:: asserted = 1

                .. data:: cleared = 2

                """

                asserted = 1

                cleared = 2


                @staticmethod
                def _meta_info():
                    from ydk.models.cisco_ios_xe._meta import _CISCO_ENTITY_ALARM_MIB as meta
                    return meta._meta_table['CiscoEntityAlarmMib.Cealarmhisttable.Cealarmhistentry.CealarmhisttypeEnum']


            @property
            def _common_path(self):
                if self.cealarmhistindex is None:
                    raise YPYModelError('Key property cealarmhistindex is None')

                return '/CISCO-ENTITY-ALARM-MIB:CISCO-ENTITY-ALARM-MIB/CISCO-ENTITY-ALARM-MIB:ceAlarmHistTable/CISCO-ENTITY-ALARM-MIB:ceAlarmHistEntry[CISCO-ENTITY-ALARM-MIB:ceAlarmHistIndex = ' + str(self.cealarmhistindex) + ']'

            def is_config(self):
                ''' Returns True if this instance represents config data else returns False '''
                return False

            def _has_data(self):
                if self.cealarmhistindex is not None:
                    return True

                if self.cealarmhistalarmtype is not None:
                    return True

                if self.cealarmhistentphysicalindex is not None:
                    return True

                if self.cealarmhistseverity is not None:
                    return True

                if self.cealarmhisttimestamp is not None:
                    return True

                if self.cealarmhisttype is not None:
                    return True

                return False

            @staticmethod
            def _meta_info():
                from ydk.models.cisco_ios_xe._meta import _CISCO_ENTITY_ALARM_MIB as meta
                return meta._meta_table['CiscoEntityAlarmMib.Cealarmhisttable.Cealarmhistentry']['meta_info']

        @property
        def _common_path(self):

            return '/CISCO-ENTITY-ALARM-MIB:CISCO-ENTITY-ALARM-MIB/CISCO-ENTITY-ALARM-MIB:ceAlarmHistTable'

        def is_config(self):
            ''' Returns True if this instance represents config data else returns False '''
            return False

        def _has_data(self):
            if self.cealarmhistentry is not None:
                for child_ref in self.cealarmhistentry:
                    if child_ref._has_data():
                        return True

            return False

        @staticmethod
        def _meta_info():
            from ydk.models.cisco_ios_xe._meta import _CISCO_ENTITY_ALARM_MIB as meta
            return meta._meta_table['CiscoEntityAlarmMib.Cealarmhisttable']['meta_info']


    class Cealarmfilterprofiletable(object):
        """
        This table contains a list of alarm filter profiles.
        
        .. attribute:: cealarmfilterprofileentry
        
        	When a physical entity asserts/clears an alarm AND the ceAlarmFilterProfile object is not '0', the agent applies the specified alarm filter profile in processing the alarm. The agent uses the following procedure in processing the transition of an alarm condition of a given type\:  1)  If the alarm list specified by the alarm filter profile's     ceAlarmFilterAlarmsEnabled object specifies that the alarm     type is disabled, then the agent performs no further     processing.  2)  The agent creates an entry in the ceAlarmHistTable.  3)  If the alarm list specified by the alarm filter profile's      ceAlarmFilterNotifiesEnabled object specifies that the alarm     type is enabled, then the agent generates the appropriate     notification.  4)  If the alarm list specified by the alarm filter profile's     ceAlarmFilterSyslogEnabled object specifies that the alarm     type is enabled, then the agent generates the appropriate     syslog message
        	**type**\: list of    :py:class:`Cealarmfilterprofileentry <ydk.models.cisco_ios_xe.CISCO_ENTITY_ALARM_MIB.CiscoEntityAlarmMib.Cealarmfilterprofiletable.Cealarmfilterprofileentry>`
        
        

        """

        _prefix = 'CISCO-ENTITY-ALARM-MIB'
        _revision = '1999-07-06'

        def __init__(self):
            self.parent = None
            self.cealarmfilterprofileentry = YList()
            self.cealarmfilterprofileentry.parent = self
            self.cealarmfilterprofileentry.name = 'cealarmfilterprofileentry'


        class Cealarmfilterprofileentry(object):
            """
            When a physical entity asserts/clears an alarm AND the
            ceAlarmFilterProfile object is not '0', the agent applies
            the specified alarm filter profile in processing the alarm.
            The agent uses the following procedure in processing the
            transition of an alarm condition of a given type\:
            
            1)  If the alarm list specified by the alarm filter profile's
                ceAlarmFilterAlarmsEnabled object specifies that the alarm
                type is disabled, then the agent performs no further
                processing.
            
            2)  The agent creates an entry in the ceAlarmHistTable.
            
            3)  If the alarm list specified by the alarm filter profile's 
                ceAlarmFilterNotifiesEnabled object specifies that the alarm
                type is enabled, then the agent generates the appropriate
                notification.
            
            4)  If the alarm list specified by the alarm filter profile's
                ceAlarmFilterSyslogEnabled object specifies that the alarm
                type is enabled, then the agent generates the appropriate
                syslog message.
            
            .. attribute:: cealarmfilterindex  <key>
            
            	This object uniquely identifies the alarm filter profile
            	**type**\:  int
            
            	**range:** 0..4294967295
            
            .. attribute:: cealarmfilteralarmsenabled
            
            	This object specifies a list of alarms that are enabled
            	**type**\:  str
            
            	**length:** 0..32
            
            .. attribute:: cealarmfilteralias
            
            	This object specifies an arbitrary name associated with the alarm filter profile by the management client, and provides a non\-volatile 'handle' for the alarm filter profile.  On the first instantiation of an alarm filter profile, the value of this object is a zero\-length string.  However, an agent may choose to set the value to a locally unique default value.  If an implementation supports write access to this object, then the agent is responsible for ensuring the retention of any value written to this object until a management client deletes it.  The level of retention must span reboots and  reinitializations of the network management system, including those that result in different assignments to the value of the entPhysicalIndex associated with the physical entity
            	**type**\:  str
            
            .. attribute:: cealarmfilternotifiesenabled
            
            	This object specifies a list of alarms for which notification generation is enabled
            	**type**\:  str
            
            	**length:** 0..32
            
            .. attribute:: cealarmfilterstatus
            
            	This object facilitates the creation, modification, or  deletion of a conceptual row in this table.  A management client can create a conceptual row in this table by setting this object to 'createAndWait' or  'createAndGo'.  If a request to create a conceptual row in this table fails, then the system is not capable of supporting any more alarm filters.  Before modifying a conceptual row in this table, the  management client must set this object to 'notInService'. After modifying a conceptual row in this table, the  management client must set this object to 'active'. This operation causes the modifications made to an alarm filter profile to take effect.  An implementation should not allow a conceptual row in this table to be deleted if one or more physical entities reference it
            	**type**\:   :py:class:`RowstatusEnum <ydk.models.cisco_ios_xe.SNMPv2_TC.RowstatusEnum>`
            
            .. attribute:: cealarmfiltersyslogenabled
            
            	This object specifies a list of alarms for which syslog message generation is enabled
            	**type**\:  str
            
            	**length:** 0..32
            
            

            """

            _prefix = 'CISCO-ENTITY-ALARM-MIB'
            _revision = '1999-07-06'

            def __init__(self):
                self.parent = None
                self.cealarmfilterindex = None
                self.cealarmfilteralarmsenabled = None
                self.cealarmfilteralias = None
                self.cealarmfilternotifiesenabled = None
                self.cealarmfilterstatus = None
                self.cealarmfiltersyslogenabled = None

            @property
            def _common_path(self):
                if self.cealarmfilterindex is None:
                    raise YPYModelError('Key property cealarmfilterindex is None')

                return '/CISCO-ENTITY-ALARM-MIB:CISCO-ENTITY-ALARM-MIB/CISCO-ENTITY-ALARM-MIB:ceAlarmFilterProfileTable/CISCO-ENTITY-ALARM-MIB:ceAlarmFilterProfileEntry[CISCO-ENTITY-ALARM-MIB:ceAlarmFilterIndex = ' + str(self.cealarmfilterindex) + ']'

            def is_config(self):
                ''' Returns True if this instance represents config data else returns False '''
                return False

            def _has_data(self):
                if self.cealarmfilterindex is not None:
                    return True

                if self.cealarmfilteralarmsenabled is not None:
                    return True

                if self.cealarmfilteralias is not None:
                    return True

                if self.cealarmfilternotifiesenabled is not None:
                    return True

                if self.cealarmfilterstatus is not None:
                    return True

                if self.cealarmfiltersyslogenabled is not None:
                    return True

                return False

            @staticmethod
            def _meta_info():
                from ydk.models.cisco_ios_xe._meta import _CISCO_ENTITY_ALARM_MIB as meta
                return meta._meta_table['CiscoEntityAlarmMib.Cealarmfilterprofiletable.Cealarmfilterprofileentry']['meta_info']

        @property
        def _common_path(self):

            return '/CISCO-ENTITY-ALARM-MIB:CISCO-ENTITY-ALARM-MIB/CISCO-ENTITY-ALARM-MIB:ceAlarmFilterProfileTable'

        def is_config(self):
            ''' Returns True if this instance represents config data else returns False '''
            return False

        def _has_data(self):
            if self.cealarmfilterprofileentry is not None:
                for child_ref in self.cealarmfilterprofileentry:
                    if child_ref._has_data():
                        return True

            return False

        @staticmethod
        def _meta_info():
            from ydk.models.cisco_ios_xe._meta import _CISCO_ENTITY_ALARM_MIB as meta
            return meta._meta_table['CiscoEntityAlarmMib.Cealarmfilterprofiletable']['meta_info']

    @property
    def _common_path(self):

        return '/CISCO-ENTITY-ALARM-MIB:CISCO-ENTITY-ALARM-MIB'

    def is_config(self):
        ''' Returns True if this instance represents config data else returns False '''
        return False

    def _has_data(self):
        if self.cealarmdescrmaptable is not None and self.cealarmdescrmaptable._has_data():
            return True

        if self.cealarmdescrtable is not None and self.cealarmdescrtable._has_data():
            return True

        if self.cealarmfiltering is not None and self.cealarmfiltering._has_data():
            return True

        if self.cealarmfilterprofiletable is not None and self.cealarmfilterprofiletable._has_data():
            return True

        if self.cealarmhistory is not None and self.cealarmhistory._has_data():
            return True

        if self.cealarmhisttable is not None and self.cealarmhisttable._has_data():
            return True

        if self.cealarmmonitoring is not None and self.cealarmmonitoring._has_data():
            return True

        if self.cealarmtable is not None and self.cealarmtable._has_data():
            return True

        return False

    @staticmethod
    def _meta_info():
        from ydk.models.cisco_ios_xe._meta import _CISCO_ENTITY_ALARM_MIB as meta
        return meta._meta_table['CiscoEntityAlarmMib']['meta_info']


