""" CISCO_SYSLOG_MIB 

The MIB module to describe and store the system
messages generated by the IOS and any other
OS which supports syslogs.

"""


import re
import collections

from enum import Enum

from ydk.types import Empty, YList, DELETE, Decimal64, FixedBitsDict

from ydk.errors import YPYError, YPYDataValidationError


from ydk.models.inet.INET_ADDRESS_MIB import InetAddressType_Enum
from ydk.models.snmpv2.SNMPv2_TC import RowStatus_Enum

class SyslogSeverity_Enum(Enum):
    """
    SyslogSeverity_Enum

    The severity of a syslog message.  The enumeration
    values are equal to the values that syslog uses + 1.
    For example, with syslog, emergency=0.
    
     'emergency' \: system is unusable
     'alert'     \: action must be taken immediately
     'critical'  \: critical conditions
     'error'     \: error conditions
     'warning'   \: warning conditions
     'notice'    \: normal but significant condition
     'informational'\: informational messages 
     'debug'        \: debug\-level messages.

    """

    EMERGENCY = 1

    ALERT = 2

    CRITICAL = 3

    ERROR = 4

    WARNING = 5

    NOTICE = 6

    INFO = 7

    DEBUG = 8


    @staticmethod
    def _meta_info():
        from ydk.models.syslog._meta import _CISCO_SYSLOG_MIB as meta
        return meta._meta_table['SyslogSeverity_Enum']



class CISCOSYSLOGMIB(object):
    """
    
    
    .. attribute:: clogbasic
    
    	
    	**type**\: :py:class:`ClogBasic <ydk.models.syslog.CISCO_SYSLOG_MIB.CISCOSYSLOGMIB.ClogBasic>`
    
    .. attribute:: cloghistory
    
    	
    	**type**\: :py:class:`ClogHistory <ydk.models.syslog.CISCO_SYSLOG_MIB.CISCOSYSLOGMIB.ClogHistory>`
    
    .. attribute:: cloghistorytable
    
    	A table of syslog messages generated by this device. All 'interesting' syslog messages (i.e. severity <= clogMaxSeverity) are entered into this table
    	**type**\: :py:class:`ClogHistoryTable <ydk.models.syslog.CISCO_SYSLOG_MIB.CISCOSYSLOGMIB.ClogHistoryTable>`
    
    .. attribute:: clogserver
    
    	
    	**type**\: :py:class:`ClogServer <ydk.models.syslog.CISCO_SYSLOG_MIB.CISCOSYSLOGMIB.ClogServer>`
    
    .. attribute:: clogserverconfigtable
    
    	This table contains entries that allow application to configure syslog servers for the system.  The maximum number of entries that can be created for this table is limited by the object clogMaxServers
    	**type**\: :py:class:`ClogServerConfigTable <ydk.models.syslog.CISCO_SYSLOG_MIB.CISCOSYSLOGMIB.ClogServerConfigTable>`
    
    

    """

    _prefix = 'cisco-syslog'
    _revision = '2005-12-03'

    def __init__(self):
        self.clogbasic = CISCOSYSLOGMIB.ClogBasic()
        self.clogbasic.parent = self
        self.cloghistory = CISCOSYSLOGMIB.ClogHistory()
        self.cloghistory.parent = self
        self.cloghistorytable = CISCOSYSLOGMIB.ClogHistoryTable()
        self.cloghistorytable.parent = self
        self.clogserver = CISCOSYSLOGMIB.ClogServer()
        self.clogserver.parent = self
        self.clogserverconfigtable = CISCOSYSLOGMIB.ClogServerConfigTable()
        self.clogserverconfigtable.parent = self


    class ClogBasic(object):
        """
        
        
        .. attribute:: clogmaxseverity
        
        	Indicates which syslog severity levels will be processed.  Any syslog message with a severity value greater than this value will be ignored by the agent. note\: severity numeric values increase as their severity decreases, e.g. 'error' is more severe than 'debug'
        	**type**\: :py:class:`SyslogSeverity_Enum <ydk.models.syslog.CISCO_SYSLOG_MIB.SyslogSeverity_Enum>`
        
        .. attribute:: clogmsgdrops
        
        	The number of syslog messages which could not be processed due to lack of system resources. Most likely this will occur at the same time that syslog messages are generated to indicate this lack of resources.  Increases in this object's value may serve as an indication that system resource levels should be examined via other mib objects.  A message that is dropped will not appear in the history table and no notification will be sent for this message
        	**type**\: int
        
        	**range:** 0..4294967295
        
        .. attribute:: clogmsgignores
        
        	The number of syslog messages which were ignored.  A message will be ignored if it has a severity value greater than clogMaxSeverity
        	**type**\: int
        
        	**range:** 0..4294967295
        
        .. attribute:: clognotificationsenabled
        
        	Indicates whether clogMessageGenerated notifications will or will not be sent when a syslog message is generated by the device.  Disabling notifications does not prevent syslog messages from being added to the clogHistoryTable
        	**type**\: bool
        
        .. attribute:: clognotificationssent
        
        	The number of clogMessageGenerated notifications that have been sent. This number may include notifications that were prevented from being transmitted due to reasons such as resource limitations and/or non\-connectivity.  If one is receiving notifications, one can periodically poll this object to determine if any notifications were missed.  If so, a poll of the clogHistoryTable might be appropriate
        	**type**\: int
        
        	**range:** 0..4294967295
        
        .. attribute:: clogoriginid
        
        	This object is used for configuring the origin identifier for the syslog messages.  The origin identifier is useful for identifying  the source of system logging messages in cases  syslog messages from multiple devices are sent  to a single syslog host. The origin identifier is added to the beginning of all system logging (syslog) messages sent to remote  hosts.  The type of the identifier is specified by clogOriginIDType object.  This object can be written by the SNMP manager only when clogOriginIDType is set to 'userDefined'.  For following value(s) of clogOriginIDType, this object can not be set; the value of this object is derived by the system in these cases\:    'contextName'     'ipv4Address'    'hostName'    'other'         'none'       This object contains the context name of the device, when clogOriginIDType is  set to 'contextName'.  This object contains IPv4 address (in dotted decimal notation) of the sending  interface when clogOriginIDType is set to 'ipv4Address'.  This object contains hostname of the system when clogOriginIDType is set to 'hostName'.  This object will contain zero length octet string when clogOriginIDType is either 'none' or 'other'
        	**type**\: str
        
        	**range:** 0..255
        
        .. attribute:: clogoriginidtype
        
        	This object identifies the type of value that will be contained in clogOriginID object.  The possible value(s) are\:    'none'       \: do not send origin identifier in                    syslog messages.    'other'      \: type that is not identified by other                    values specified in this object.    'hostName'   \: Send hostname of the system in syslog                   messages.    'ipv4Address'\: Send IP address of the sending interface.    'contextName'\: Send context name of the security device.    'userDefined'\: Send user configured string in                   syslog message.     The value 'other' and 'none' can not be set but    can only be read
        	**type**\: :py:class:`ClogOriginIDType_Enum <ydk.models.syslog.CISCO_SYSLOG_MIB.CISCOSYSLOGMIB.ClogBasic.ClogOriginIDType_Enum>`
        
        

        """

        _prefix = 'cisco-syslog'
        _revision = '2005-12-03'

        def __init__(self):
            self.parent = None
            self.clogmaxseverity = None
            self.clogmsgdrops = None
            self.clogmsgignores = None
            self.clognotificationsenabled = None
            self.clognotificationssent = None
            self.clogoriginid = None
            self.clogoriginidtype = None

        class ClogOriginIDType_Enum(Enum):
            """
            ClogOriginIDType_Enum

            This object identifies the type of value that
            will be contained in clogOriginID object.
            
            The possible value(s) are\:
               'none'       \: do not send origin identifier in 
                              syslog messages.
               'other'      \: type that is not identified by other 
                              values specified in this object.
               'hostName'   \: Send hostname of the system in syslog
                              messages.
               'ipv4Address'\: Send IP address of the sending interface.
               'contextName'\: Send context name of the security device.
               'userDefined'\: Send user configured string in
                              syslog message.
            
               The value 'other' and 'none' can not be set but
               can only be read.

            """

            NONE = 1

            OTHER = 2

            HOSTNAME = 3

            IPV4ADDRESS = 4

            CONTEXTNAME = 5

            USERDEFINED = 6


            @staticmethod
            def _meta_info():
                from ydk.models.syslog._meta import _CISCO_SYSLOG_MIB as meta
                return meta._meta_table['CISCOSYSLOGMIB.ClogBasic.ClogOriginIDType_Enum']


        @property
        def _common_path(self):

            return '/CISCO-SYSLOG-MIB:CISCO-SYSLOG-MIB/CISCO-SYSLOG-MIB:clogBasic'

        def is_config(self):
            ''' Returns True if this instance represents config data else returns False '''
            return False

        def _has_data(self):
            if not self.is_config():
                return False
            if self.is_presence():
                return True
            if self.clogmaxseverity is not None:
                return True

            if self.clogmsgdrops is not None:
                return True

            if self.clogmsgignores is not None:
                return True

            if self.clognotificationsenabled is not None:
                return True

            if self.clognotificationssent is not None:
                return True

            if self.clogoriginid is not None:
                return True

            if self.clogoriginidtype is not None:
                return True

            return False

        def is_presence(self):
            ''' Returns True if this instance represents presence container else returns False '''
            return False

        @staticmethod
        def _meta_info():
            from ydk.models.syslog._meta import _CISCO_SYSLOG_MIB as meta
            return meta._meta_table['CISCOSYSLOGMIB.ClogBasic']['meta_info']


    class ClogHistory(object):
        """
        
        
        .. attribute:: cloghistmsgsflushed
        
        	The number of entries that have been removed from the clogHistoryTable in order to make room for new entries. This object can be utilized to determine whether your polling frequency on the history table is fast enough and/or the size of your history table is large enough such that you are not missing messages
        	**type**\: int
        
        	**range:** 0..4294967295
        
        .. attribute:: cloghisttablemaxlength
        
        	The upper limit on the number of entries that the clogHistoryTable may contain.  A value of 0 will prevent any history from being retained. When this table is full, the oldest entry will be deleted and a new one will be created
        	**type**\: int
        
        	**range:** 0..500
        
        

        """

        _prefix = 'cisco-syslog'
        _revision = '2005-12-03'

        def __init__(self):
            self.parent = None
            self.cloghistmsgsflushed = None
            self.cloghisttablemaxlength = None

        @property
        def _common_path(self):

            return '/CISCO-SYSLOG-MIB:CISCO-SYSLOG-MIB/CISCO-SYSLOG-MIB:clogHistory'

        def is_config(self):
            ''' Returns True if this instance represents config data else returns False '''
            return False

        def _has_data(self):
            if not self.is_config():
                return False
            if self.is_presence():
                return True
            if self.cloghistmsgsflushed is not None:
                return True

            if self.cloghisttablemaxlength is not None:
                return True

            return False

        def is_presence(self):
            ''' Returns True if this instance represents presence container else returns False '''
            return False

        @staticmethod
        def _meta_info():
            from ydk.models.syslog._meta import _CISCO_SYSLOG_MIB as meta
            return meta._meta_table['CISCOSYSLOGMIB.ClogHistory']['meta_info']


    class ClogHistoryTable(object):
        """
        A table of syslog messages generated by this device.
        All 'interesting' syslog messages (i.e. severity <=
        clogMaxSeverity) are entered into this table.
        
        .. attribute:: cloghistoryentry
        
        	A syslog message that was previously generated by this device. Each entry is indexed by a message index
        	**type**\: list of :py:class:`ClogHistoryEntry <ydk.models.syslog.CISCO_SYSLOG_MIB.CISCOSYSLOGMIB.ClogHistoryTable.ClogHistoryEntry>`
        
        

        """

        _prefix = 'cisco-syslog'
        _revision = '2005-12-03'

        def __init__(self):
            self.parent = None
            self.cloghistoryentry = YList()
            self.cloghistoryentry.parent = self
            self.cloghistoryentry.name = 'cloghistoryentry'


        class ClogHistoryEntry(object):
            """
            A syslog message that was previously generated by this
            device. Each entry is indexed by a message index.
            
            .. attribute:: cloghistindex
            
            	A monotonically increasing integer for the sole purpose of indexing messages.  When it reaches the maximum value the agent flushes the table and wraps the value back to 1
            	**type**\: int
            
            	**range:** 1..2147483647
            
            .. attribute:: cloghistfacility
            
            	Name of the facility that generated this message. For example\: 'SYS'
            	**type**\: str
            
            	**range:** 1..20
            
            .. attribute:: cloghistmsgname
            
            	A textual identification for the message type. A facility name in conjunction with a message name uniquely identifies a message type
            	**type**\: str
            
            	**range:** 1..30
            
            .. attribute:: cloghistmsgtext
            
            	The text of the message.  If the text of the message exceeds 255 bytes, the message will be truncated to 254 bytes and a '\*' character will be appended \- indicating that the message has been truncated
            	**type**\: str
            
            	**range:** 1..255
            
            .. attribute:: cloghistseverity
            
            	The severity of the message
            	**type**\: :py:class:`SyslogSeverity_Enum <ydk.models.syslog.CISCO_SYSLOG_MIB.SyslogSeverity_Enum>`
            
            .. attribute:: cloghisttimestamp
            
            	The value of sysUpTime when this message was generated
            	**type**\: int
            
            	**range:** 0..4294967295
            
            

            """

            _prefix = 'cisco-syslog'
            _revision = '2005-12-03'

            def __init__(self):
                self.parent = None
                self.cloghistindex = None
                self.cloghistfacility = None
                self.cloghistmsgname = None
                self.cloghistmsgtext = None
                self.cloghistseverity = None
                self.cloghisttimestamp = None

            @property
            def _common_path(self):
                if self.cloghistindex is None:
                    raise YPYDataValidationError('Key property cloghistindex is None')

                return '/CISCO-SYSLOG-MIB:CISCO-SYSLOG-MIB/CISCO-SYSLOG-MIB:clogHistoryTable/CISCO-SYSLOG-MIB:clogHistoryEntry[CISCO-SYSLOG-MIB:clogHistIndex = ' + str(self.cloghistindex) + ']'

            def is_config(self):
                ''' Returns True if this instance represents config data else returns False '''
                return False

            def _has_data(self):
                if not self.is_config():
                    return False
                if self.is_presence():
                    return True
                if self.cloghistindex is not None:
                    return True

                if self.cloghistfacility is not None:
                    return True

                if self.cloghistmsgname is not None:
                    return True

                if self.cloghistmsgtext is not None:
                    return True

                if self.cloghistseverity is not None:
                    return True

                if self.cloghisttimestamp is not None:
                    return True

                return False

            def is_presence(self):
                ''' Returns True if this instance represents presence container else returns False '''
                return False

            @staticmethod
            def _meta_info():
                from ydk.models.syslog._meta import _CISCO_SYSLOG_MIB as meta
                return meta._meta_table['CISCOSYSLOGMIB.ClogHistoryTable.ClogHistoryEntry']['meta_info']

        @property
        def _common_path(self):

            return '/CISCO-SYSLOG-MIB:CISCO-SYSLOG-MIB/CISCO-SYSLOG-MIB:clogHistoryTable'

        def is_config(self):
            ''' Returns True if this instance represents config data else returns False '''
            return False

        def _has_data(self):
            if not self.is_config():
                return False
            if self.is_presence():
                return True
            if self.cloghistoryentry is not None:
                for child_ref in self.cloghistoryentry:
                    if child_ref._has_data():
                        return True

            return False

        def is_presence(self):
            ''' Returns True if this instance represents presence container else returns False '''
            return False

        @staticmethod
        def _meta_info():
            from ydk.models.syslog._meta import _CISCO_SYSLOG_MIB as meta
            return meta._meta_table['CISCOSYSLOGMIB.ClogHistoryTable']['meta_info']


    class ClogServer(object):
        """
        
        
        .. attribute:: clogmaxservers
        
        	The maximum number of syslog servers that can be configured for the system in clogServerConfigTable.  A value of zero for this object indicates there is no specified limit for the system and is only dictated by system resources
        	**type**\: int
        
        	**range:** 0..4294967295
        
        

        """

        _prefix = 'cisco-syslog'
        _revision = '2005-12-03'

        def __init__(self):
            self.parent = None
            self.clogmaxservers = None

        @property
        def _common_path(self):

            return '/CISCO-SYSLOG-MIB:CISCO-SYSLOG-MIB/CISCO-SYSLOG-MIB:clogServer'

        def is_config(self):
            ''' Returns True if this instance represents config data else returns False '''
            return False

        def _has_data(self):
            if not self.is_config():
                return False
            if self.is_presence():
                return True
            if self.clogmaxservers is not None:
                return True

            return False

        def is_presence(self):
            ''' Returns True if this instance represents presence container else returns False '''
            return False

        @staticmethod
        def _meta_info():
            from ydk.models.syslog._meta import _CISCO_SYSLOG_MIB as meta
            return meta._meta_table['CISCOSYSLOGMIB.ClogServer']['meta_info']


    class ClogServerConfigTable(object):
        """
        This table contains entries that allow application
        to configure syslog servers for the system.
        
        The maximum number of entries that can be created
        for this table is limited by the object
        clogMaxServers.
        
        .. attribute:: clogserverconfigentry
        
        	An entry containing information about syslog servers configured for the system
        	**type**\: list of :py:class:`ClogServerConfigEntry <ydk.models.syslog.CISCO_SYSLOG_MIB.CISCOSYSLOGMIB.ClogServerConfigTable.ClogServerConfigEntry>`
        
        

        """

        _prefix = 'cisco-syslog'
        _revision = '2005-12-03'

        def __init__(self):
            self.parent = None
            self.clogserverconfigentry = YList()
            self.clogserverconfigentry.parent = self
            self.clogserverconfigentry.name = 'clogserverconfigentry'


        class ClogServerConfigEntry(object):
            """
            An entry containing information about syslog servers
            configured for the system.
            
            .. attribute:: clogserveraddr
            
            	The Internet address of this syslog server. The type of this address is determined by the value of the clogServerAddrType object
            	**type**\: str
            
            	**range:** 0..64
            
            .. attribute:: clogserveraddrtype
            
            	The type of Internet address of this syslog server
            	**type**\: :py:class:`InetAddressType_Enum <ydk.models.inet.INET_ADDRESS_MIB.InetAddressType_Enum>`
            
            .. attribute:: clogserverstatus
            
            	The status object used to manage rows in this table.  A row may only be created by setting this object to 'createAndGo'.  A row may only be deleted by setting this object to 'destroy'
            	**type**\: :py:class:`RowStatus_Enum <ydk.models.snmpv2.SNMPv2_TC.RowStatus_Enum>`
            
            

            """

            _prefix = 'cisco-syslog'
            _revision = '2005-12-03'

            def __init__(self):
                self.parent = None
                self.clogserveraddr = None
                self.clogserveraddrtype = None
                self.clogserverstatus = None

            @property
            def _common_path(self):
                if self.clogserveraddr is None:
                    raise YPYDataValidationError('Key property clogserveraddr is None')
                if self.clogserveraddrtype is None:
                    raise YPYDataValidationError('Key property clogserveraddrtype is None')

                return '/CISCO-SYSLOG-MIB:CISCO-SYSLOG-MIB/CISCO-SYSLOG-MIB:clogServerConfigTable/CISCO-SYSLOG-MIB:clogServerConfigEntry[CISCO-SYSLOG-MIB:clogServerAddr = ' + str(self.clogserveraddr) + '][CISCO-SYSLOG-MIB:clogServerAddrType = ' + str(self.clogserveraddrtype) + ']'

            def is_config(self):
                ''' Returns True if this instance represents config data else returns False '''
                return False

            def _has_data(self):
                if not self.is_config():
                    return False
                if self.is_presence():
                    return True
                if self.clogserveraddr is not None:
                    return True

                if self.clogserveraddrtype is not None:
                    return True

                if self.clogserverstatus is not None:
                    return True

                return False

            def is_presence(self):
                ''' Returns True if this instance represents presence container else returns False '''
                return False

            @staticmethod
            def _meta_info():
                from ydk.models.syslog._meta import _CISCO_SYSLOG_MIB as meta
                return meta._meta_table['CISCOSYSLOGMIB.ClogServerConfigTable.ClogServerConfigEntry']['meta_info']

        @property
        def _common_path(self):

            return '/CISCO-SYSLOG-MIB:CISCO-SYSLOG-MIB/CISCO-SYSLOG-MIB:clogServerConfigTable'

        def is_config(self):
            ''' Returns True if this instance represents config data else returns False '''
            return False

        def _has_data(self):
            if not self.is_config():
                return False
            if self.is_presence():
                return True
            if self.clogserverconfigentry is not None:
                for child_ref in self.clogserverconfigentry:
                    if child_ref._has_data():
                        return True

            return False

        def is_presence(self):
            ''' Returns True if this instance represents presence container else returns False '''
            return False

        @staticmethod
        def _meta_info():
            from ydk.models.syslog._meta import _CISCO_SYSLOG_MIB as meta
            return meta._meta_table['CISCOSYSLOGMIB.ClogServerConfigTable']['meta_info']

    @property
    def _common_path(self):

        return '/CISCO-SYSLOG-MIB:CISCO-SYSLOG-MIB'

    def is_config(self):
        ''' Returns True if this instance represents config data else returns False '''
        return False

    def _has_data(self):
        if not self.is_config():
            return False
        if self.is_presence():
            return True
        if self.clogbasic is not None and self.clogbasic._has_data():
            return True

        if self.clogbasic is not None and self.clogbasic.is_presence():
            return True

        if self.cloghistory is not None and self.cloghistory._has_data():
            return True

        if self.cloghistory is not None and self.cloghistory.is_presence():
            return True

        if self.cloghistorytable is not None and self.cloghistorytable._has_data():
            return True

        if self.cloghistorytable is not None and self.cloghistorytable.is_presence():
            return True

        if self.clogserver is not None and self.clogserver._has_data():
            return True

        if self.clogserver is not None and self.clogserver.is_presence():
            return True

        if self.clogserverconfigtable is not None and self.clogserverconfigtable._has_data():
            return True

        if self.clogserverconfigtable is not None and self.clogserverconfigtable.is_presence():
            return True

        return False

    def is_presence(self):
        ''' Returns True if this instance represents presence container else returns False '''
        return False

    @staticmethod
    def _meta_info():
        from ydk.models.syslog._meta import _CISCO_SYSLOG_MIB as meta
        return meta._meta_table['CISCOSYSLOGMIB']['meta_info']


