


import re
import collections

from enum import Enum

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk.types import Empty, YList, YLeafList, DELETE, Decimal64, FixedBitsDict
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_CLASS, REFERENCE_LIST, REFERENCE_LEAFLIST,     REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, REFERENCE_BITS, REFERENCE_UNION

from ydk.errors import YPYError, YPYModelError
from ydk.providers._importer import _yang_ns

_meta_table = {
    'MplSeeds.BufferedMessages' : {
        'meta_info' : _MetaInfoClass('MplSeeds.BufferedMessages',
            False, 
            [
            _MetaInfoClassMember('seqno', ATTRIBUTE, 'int' , None, None, 
                [('0', '255')], [], 
                '''                Sequence number of message.
                ''',
                'seqno',
                'ietf-yang-mpl-seeds', True),
            _MetaInfoClassMember('c', ATTRIBUTE, 'int' , None, None, 
                [('0', '255')], [], 
                '''                number of times that copy of this message has been
                received in this interval.
                ''',
                'c',
                'ietf-yang-mpl-seeds', False),
            _MetaInfoClassMember('e', ATTRIBUTE, 'int' , None, None, 
                [('0', '255')], [], 
                '''                number of Trickle time expirations since last
                Trickle timer reset.
                ''',
                'e',
                'ietf-yang-mpl-seeds', False),
            _MetaInfoClassMember('I', ATTRIBUTE, 'int' , None, None, 
                [('0', '255')], [], 
                '''                Current Trickle timer interval size in SE-LIFETIME
                units.
                ''',
                'i',
                'ietf-yang-mpl-seeds', False),
            _MetaInfoClassMember('t', ATTRIBUTE, 'int' , None, None, 
                [('0', '255')], [], 
                '''                 Time expressed in SE-LIFETIME units
                that message will be (is) forwarded
                ''',
                't',
                'ietf-yang-mpl-seeds', False),
            ],
            'ietf-yang-mpl-seeds',
            'buffered-messages',
            _yang_ns._namespaces['ietf-yang-mpl-seeds'],
        'ydk.models.ietf.ietf_yang_mpl_seeds'
        ),
    },
    'MplSeeds' : {
        'meta_info' : _MetaInfoClass('MplSeeds',
            False, 
            [
            _MetaInfoClassMember('domainID', ATTRIBUTE, 'int' , None, None, 
                [('0', '65535')], [], 
                '''                together with seedID uniquely identifies buffer set.
                ''',
                'domainid',
                'ietf-yang-mpl-seeds', True),
            _MetaInfoClassMember('seedID', ATTRIBUTE, 'int' , None, None, 
                [('0', '18446744073709551615')], [], 
                '''                value uniquely identifies the MPL Seed within a MPL
                domain.
                ''',
                'seedid',
                'ietf-yang-mpl-seeds', True),
            _MetaInfoClassMember('buffered-messages', REFERENCE_LIST, 'BufferedMessages' , 'ydk.models.ietf.ietf_yang_mpl_seeds', 'MplSeeds.BufferedMessages', 
                [], [], 
                '''                 status of trickle intervals of the buffered message
                identified by seqno. and seed/domain
                ''',
                'buffered_messages',
                'ietf-yang-mpl-seeds', False),
            _MetaInfoClassMember('control-number', ATTRIBUTE, 'int' , None, None, 
                [('0', '255')], [], 
                '''                Number of currently buffered control messages.
                ''',
                'control_number',
                'ietf-yang-mpl-seeds', False),
            _MetaInfoClassMember('data-number', ATTRIBUTE, 'int' , None, None, 
                [('0', '255')], [], 
                '''                Number of currently buffered data messages.
                ''',
                'data_number',
                'ietf-yang-mpl-seeds', False),
            _MetaInfoClassMember('generate-seqno', ATTRIBUTE, 'int' , None, None, 
                [('0', '255')], [], 
                '''                Sequence number of next message to be generated by
                this local seed.
                ''',
                'generate_seqno',
                'ietf-yang-mpl-seeds', False),
            _MetaInfoClassMember('life-time', ATTRIBUTE, 'int' , None, None, 
                [('0', '18446744073709551615')], [], 
                '''                 Minimum remaining lifetime of the seed entry in
                SE_LIFETIME units.
                ''',
                'life_time',
                'ietf-yang-mpl-seeds', False),
            _MetaInfoClassMember('local', ATTRIBUTE, 'bool' , None, None, 
                [], [], 
                '''                When local == TRUE, seed is located in this forwarder.
                WHEN local == false, seed is located in different
                forwarder.
                ''',
                'local',
                'ietf-yang-mpl-seeds', False),
            _MetaInfoClassMember('min-seqno', ATTRIBUTE, 'int' , None, None, 
                [('0', '255')], [], 
                '''                Lower bound sequence number in the buffer of the seed.
                ''',
                'min_seqno',
                'ietf-yang-mpl-seeds', False),
            ],
            'ietf-yang-mpl-seeds',
            'mpl-seeds',
            _yang_ns._namespaces['ietf-yang-mpl-seeds'],
        'ydk.models.ietf.ietf_yang_mpl_seeds'
        ),
    },
}
_meta_table['MplSeeds.BufferedMessages']['meta_info'].parent =_meta_table['MplSeeds']['meta_info']
