


import re
import collections

from enum import Enum

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum, _dm_validate_value
from ydk.types import Empty, YList, DELETE, Decimal64, FixedBitsDict
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_CLASS, REFERENCE_LIST, REFERENCE_LEAFLIST,     REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, REFERENCE_BITS, REFERENCE_UNION

from ydk.errors import YPYError, YPYDataValidationError
from ydk.models import _yang_ns

_meta_table = {
    'SnmpEnableAuthenTrapsType_Enum' : _MetaInfoEnum('SnmpEnableAuthenTrapsType_Enum', 'ydk.models.snmpv2.SNMPv2_MIB',
        {
            'enabled':'ENABLED',
            'disabled':'DISABLED',
        }, 'SNMPv2-MIB', _yang_ns._namespaces['SNMPv2-MIB']),
    'SNMPv2MIB.Snmp' : {
        'meta_info' : _MetaInfoClass('SNMPv2MIB.Snmp',
            False, 
            [
            _MetaInfoClassMember('snmpEnableAuthenTraps', REFERENCE_ENUM_CLASS, 'SnmpEnableAuthenTrapsType_Enum' , 'ydk.models.snmpv2.SNMPv2_MIB', 'SnmpEnableAuthenTrapsType_Enum', 
                [], [], 
                '''                ''',
                'snmpenableauthentraps',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('snmpInASNParseErrs', ATTRIBUTE, 'int' , None, None, 
                [(0, 4294967295)], [], 
                '''                ''',
                'snmpinasnparseerrs',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('snmpInBadCommunityNames', ATTRIBUTE, 'int' , None, None, 
                [(0, 4294967295)], [], 
                '''                ''',
                'snmpinbadcommunitynames',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('snmpInBadCommunityUses', ATTRIBUTE, 'int' , None, None, 
                [(0, 4294967295)], [], 
                '''                ''',
                'snmpinbadcommunityuses',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('snmpInBadVersions', ATTRIBUTE, 'int' , None, None, 
                [(0, 4294967295)], [], 
                '''                ''',
                'snmpinbadversions',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('snmpInPkts', ATTRIBUTE, 'int' , None, None, 
                [(0, 4294967295)], [], 
                '''                ''',
                'snmpinpkts',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('snmpProxyDrops', ATTRIBUTE, 'int' , None, None, 
                [(0, 4294967295)], [], 
                '''                ''',
                'snmpproxydrops',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('snmpSilentDrops', ATTRIBUTE, 'int' , None, None, 
                [(0, 4294967295)], [], 
                '''                ''',
                'snmpsilentdrops',
                'SNMPv2-MIB', False),
            ],
            'SNMPv2-MIB',
            'snmp',
            _yang_ns._namespaces['SNMPv2-MIB'],
        'ydk.models.snmpv2.SNMPv2_MIB'
        ),
    },
    'SNMPv2MIB.SnmpSet' : {
        'meta_info' : _MetaInfoClass('SNMPv2MIB.SnmpSet',
            False, 
            [
            _MetaInfoClassMember('snmpSetSerialNo', ATTRIBUTE, 'int' , None, None, 
                [(0, 2147483647)], [], 
                '''                ''',
                'snmpsetserialno',
                'SNMPv2-MIB', False),
            ],
            'SNMPv2-MIB',
            'snmpSet',
            _yang_ns._namespaces['SNMPv2-MIB'],
        'ydk.models.snmpv2.SNMPv2_MIB'
        ),
    },
    'SNMPv2MIB.SysORTable.SysOREntry' : {
        'meta_info' : _MetaInfoClass('SNMPv2MIB.SysORTable.SysOREntry',
            False, 
            [
            _MetaInfoClassMember('sysORIndex', ATTRIBUTE, 'int' , None, None, 
                [(1, 2147483647)], [], 
                '''                ''',
                'sysorindex',
                'SNMPv2-MIB', True),
            _MetaInfoClassMember('sysORDescr', ATTRIBUTE, 'str' , None, None, 
                [(0, 255)], [], 
                '''                ''',
                'sysordescr',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('sysORID', ATTRIBUTE, 'str' , None, None, 
                [], ['(([0-1](\\.[1-3]?[0-9]))|(2\\.(0|([1-9]\\d*))))(\\.(0|([1-9]\\d*)))*'], 
                '''                ''',
                'sysorid',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('sysORUpTime', ATTRIBUTE, 'int' , None, None, 
                [(0, 4294967295)], [], 
                '''                ''',
                'sysoruptime',
                'SNMPv2-MIB', False),
            ],
            'SNMPv2-MIB',
            'sysOREntry',
            _yang_ns._namespaces['SNMPv2-MIB'],
        'ydk.models.snmpv2.SNMPv2_MIB'
        ),
    },
    'SNMPv2MIB.SysORTable' : {
        'meta_info' : _MetaInfoClass('SNMPv2MIB.SysORTable',
            False, 
            [
            _MetaInfoClassMember('sysOREntry', REFERENCE_LIST, 'SysOREntry' , 'ydk.models.snmpv2.SNMPv2_MIB', 'SNMPv2MIB.SysORTable.SysOREntry', 
                [], [], 
                '''                ''',
                'sysorentry',
                'SNMPv2-MIB', False),
            ],
            'SNMPv2-MIB',
            'sysORTable',
            _yang_ns._namespaces['SNMPv2-MIB'],
        'ydk.models.snmpv2.SNMPv2_MIB'
        ),
    },
    'SNMPv2MIB.System' : {
        'meta_info' : _MetaInfoClass('SNMPv2MIB.System',
            False, 
            [
            _MetaInfoClassMember('sysContact', ATTRIBUTE, 'str' , None, None, 
                [], ['\\p{IsBasicLatin}{0,255}'], 
                '''                ''',
                'syscontact',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('sysDescr', ATTRIBUTE, 'str' , None, None, 
                [], ['\\p{IsBasicLatin}{0,255}'], 
                '''                ''',
                'sysdescr',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('sysLocation', ATTRIBUTE, 'str' , None, None, 
                [], ['\\p{IsBasicLatin}{0,255}'], 
                '''                ''',
                'syslocation',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('sysName', ATTRIBUTE, 'str' , None, None, 
                [], ['\\p{IsBasicLatin}{0,255}'], 
                '''                ''',
                'sysname',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('sysObjectID', ATTRIBUTE, 'str' , None, None, 
                [], ['(([0-1](\\.[1-3]?[0-9]))|(2\\.(0|([1-9]\\d*))))(\\.(0|([1-9]\\d*)))*'], 
                '''                ''',
                'sysobjectid',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('sysORLastChange', ATTRIBUTE, 'int' , None, None, 
                [(0, 4294967295)], [], 
                '''                ''',
                'sysorlastchange',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('sysServices', ATTRIBUTE, 'int' , None, None, 
                [(0, 127)], [], 
                '''                ''',
                'sysservices',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('sysUpTime', ATTRIBUTE, 'int' , None, None, 
                [(0, 4294967295)], [], 
                '''                ''',
                'sysuptime',
                'SNMPv2-MIB', False),
            ],
            'SNMPv2-MIB',
            'system',
            _yang_ns._namespaces['SNMPv2-MIB'],
        'ydk.models.snmpv2.SNMPv2_MIB'
        ),
    },
    'SNMPv2MIB' : {
        'meta_info' : _MetaInfoClass('SNMPv2MIB',
            False, 
            [
            _MetaInfoClassMember('snmp', REFERENCE_CLASS, 'Snmp' , 'ydk.models.snmpv2.SNMPv2_MIB', 'SNMPv2MIB.Snmp', 
                [], [], 
                '''                ''',
                'snmp',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('snmpSet', REFERENCE_CLASS, 'SnmpSet' , 'ydk.models.snmpv2.SNMPv2_MIB', 'SNMPv2MIB.SnmpSet', 
                [], [], 
                '''                ''',
                'snmpset',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('sysORTable', REFERENCE_CLASS, 'SysORTable' , 'ydk.models.snmpv2.SNMPv2_MIB', 'SNMPv2MIB.SysORTable', 
                [], [], 
                '''                ''',
                'sysortable',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('system', REFERENCE_CLASS, 'System' , 'ydk.models.snmpv2.SNMPv2_MIB', 'SNMPv2MIB.System', 
                [], [], 
                '''                ''',
                'system',
                'SNMPv2-MIB', False),
            ],
            'SNMPv2-MIB',
            'SNMPv2-MIB',
            _yang_ns._namespaces['SNMPv2-MIB'],
        'ydk.models.snmpv2.SNMPv2_MIB'
        ),
    },
}
_meta_table['SNMPv2MIB.SysORTable.SysOREntry']['meta_info'].parent =_meta_table['SNMPv2MIB.SysORTable']['meta_info']
_meta_table['SNMPv2MIB.Snmp']['meta_info'].parent =_meta_table['SNMPv2MIB']['meta_info']
_meta_table['SNMPv2MIB.SnmpSet']['meta_info'].parent =_meta_table['SNMPv2MIB']['meta_info']
_meta_table['SNMPv2MIB.SysORTable']['meta_info'].parent =_meta_table['SNMPv2MIB']['meta_info']
_meta_table['SNMPv2MIB.System']['meta_info'].parent =_meta_table['SNMPv2MIB']['meta_info']
