


import re
import collections

from enum import Enum

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk.types import Empty, YList, YLeafList, DELETE, Decimal64, FixedBitsDict
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_CLASS, REFERENCE_LIST, REFERENCE_LEAFLIST,     REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, REFERENCE_BITS, REFERENCE_UNION

from ydk.errors import YPYError, YPYModelError
from ydk.providers._importer import _yang_ns

_meta_table = {
    'LptsPreIFibPrecedenceNumberEnum' : _MetaInfoEnum('LptsPreIFibPrecedenceNumberEnum', 'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lpts_pre_ifib_cfg',
        {
            'critical':'CRITICAL',
            'flash':'FLASH',
            'flash-override':'FLASH_OVERRIDE',
            'immediate':'IMMEDIATE',
            'internet':'INTERNET',
            'network':'NETWORK',
            'priority':'PRIORITY',
            'routine':'ROUTINE',
        }, 'Cisco-IOS-XR-lpts-pre-ifib-cfg', _yang_ns._namespaces['Cisco-IOS-XR-lpts-pre-ifib-cfg']),
    'LptsFlowEnum' : _MetaInfoEnum('LptsFlowEnum', 'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lpts_pre_ifib_cfg',
        {
            'config-default':'CONFIG_DEFAULT',
            'l2tpv2-fragment':'L2TPV2_FRAGMENT',
            'fragment':'FRAGMENT',
            'ospf-multicast-known':'OSPF_MULTICAST_KNOWN',
            'ospf-multicast-default':'OSPF_MULTICAST_DEFAULT',
            'ospf-unicast-known':'OSPF_UNICAST_KNOWN',
            'ospf-unicast-default':'OSPF_UNICAST_DEFAULT',
            'isis-known':'ISIS_KNOWN',
            'isis-default':'ISIS_DEFAULT',
            'bfd-known':'BFD_KNOWN',
            'bfd-default':'BFD_DEFAULT',
            'bfd-multipath-known':'BFD_MULTIPATH_KNOWN',
            'bfd-multipath0':'BFD_MULTIPATH0',
            'bfd-blb-known':'BFD_BLB_KNOWN',
            'bfd-blb0':'BFD_BLB0',
            'bfd-sp0':'BFD_SP0',
            'bgp-known':'BGP_KNOWN',
            'bgp-config-peer':'BGP_CONFIG_PEER',
            'bgp-default':'BGP_DEFAULT',
            'pim-multicast-default':'PIM_MULTICAST_DEFAULT',
            'pim-multicast-known':'PIM_MULTICAST_KNOWN',
            'pim-unicast':'PIM_UNICAST',
            'igmp':'IGMP',
            'icmp-local':'ICMP_LOCAL',
            'icmp-app':'ICMP_APP',
            'icmp-control':'ICMP_CONTROL',
            'icmp-default':'ICMP_DEFAULT',
            'icmp-app-default':'ICMP_APP_DEFAULT',
            'ldp-tcp-known':'LDP_TCP_KNOWN',
            'ldp-tcp-config-peer':'LDP_TCP_CONFIG_PEER',
            'ldp-tcp-default':'LDP_TCP_DEFAULT',
            'ldp-udp':'LDP_UDP',
            'all-routers':'ALL_ROUTERS',
            'lmp-tcp-known':'LMP_TCP_KNOWN',
            'lmp-tcp-config-peer':'LMP_TCP_CONFIG_PEER',
            'lmp-tcp-default':'LMP_TCP_DEFAULT',
            'lmp-udp':'LMP_UDP',
            'rsvp-udp':'RSVP_UDP',
            'rsvp-default':'RSVP_DEFAULT',
            'rsvp-known':'RSVP_KNOWN',
            'ike':'IKE',
            'ipsec-known':'IPSEC_KNOWN',
            'ipsec-default':'IPSEC_DEFAULT',
            'ipsec-fragment':'IPSEC_FRAGMENT',
            'msdp-known':'MSDP_KNOWN',
            'msdp-config-peer':'MSDP_CONFIG_PEER',
            'msdp-default':'MSDP_DEFAULT',
            'snmp':'SNMP',
            'ssh-known':'SSH_KNOWN',
            'ssh-default':'SSH_DEFAULT',
            'http-known':'HTTP_KNOWN',
            'http-default':'HTTP_DEFAULT',
            'shttp-known':'SHTTP_KNOWN',
            'shttp-default':'SHTTP_DEFAULT',
            'telnet-known':'TELNET_KNOWN',
            'telnet-default':'TELNET_DEFAULT',
            'css-known':'CSS_KNOWN',
            'css-default':'CSS_DEFAULT',
            'rsh-known':'RSH_KNOWN',
            'rsh-default':'RSH_DEFAULT',
            'udp-known':'UDP_KNOWN',
            'udp-listen':'UDP_LISTEN',
            'udp-config-peer':'UDP_CONFIG_PEER',
            'udp-default':'UDP_DEFAULT',
            'tcp-known':'TCP_KNOWN',
            'tcp-listen':'TCP_LISTEN',
            'tcp-config-peer':'TCP_CONFIG_PEER',
            'tcp-default':'TCP_DEFAULT',
            'multicast-known':'MULTICAST_KNOWN',
            'multicast-default':'MULTICAST_DEFAULT',
            'raw-listen':'RAW_LISTEN',
            'raw-default':'RAW_DEFAULT',
            'ipsla':'IPSLA',
            'eigrp':'EIGRP',
            'rip':'RIP',
            'l2tpv3':'L2TPV3',
            'pcep-tcp-default':'PCEP_TCP_DEFAULT',
            'gre':'GRE',
            'vrrp':'VRRP',
            'hsrp':'HSRP',
            'mpls-ping':'MPLS_PING',
            'l2tpv2-default':'L2TPV2_DEFAULT',
            'l2tpv2-known':'L2TPV2_KNOWN',
            'dns':'DNS',
            'radius':'RADIUS',
            'tacacs':'TACACS',
            'ntp-default':'NTP_DEFAULT',
            'ntp-known':'NTP_KNOWN',
            'mobile-ipv6':'MOBILE_IPV6',
            'amt':'AMT',
            'sdac-tcp':'SDAC_TCP',
            'radius-coa':'RADIUS_COA',
            'rel-udp':'REL_UDP',
            'dhcp4':'DHCP4',
            'dhcp6':'DHCP6',
            'onepk':'ONEPK',
            'exr':'EXR',
        }, 'Cisco-IOS-XR-lpts-pre-ifib-cfg', _yang_ns._namespaces['Cisco-IOS-XR-lpts-pre-ifib-cfg']),
}
